**Section A (2 Marks each)**

*NumPy (Numerical Python)*

In [308]:
import numpy as np

In [309]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
a = np.random.rand(1,5)
b=np.array(a)
print(b)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
c = [[1,2,3],[3,43,5],[34,56,76]]
k = np.array(c)
print(k)


[[0.2995132  0.40430071 0.23078416 0.44077226 0.38514321]]
[[ 1  2  3]
 [ 3 43  5]
 [34 56 76]]


In [310]:
# Write a NumPy function to create an array with random values of shape [3,4]
a = np.random.rand(3,4)
print(a)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
c = np.zeros((3,4))
print(c)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
d = np.ones((3,4))
print(d)

[[0.60503335 0.14876305 0.64814956 0.49220019]
 [0.34860656 0.48843974 0.63000732 0.92204537]
 [0.88263807 0.12846497 0.21576407 0.46649769]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [311]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace

a = np.linspace(3,77,6)
print(a)

[ 3.  17.8 32.6 47.4 62.2 77. ]


In [312]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [313]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [314]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
print(a.sum(axis=0))

# Write a NumPy function to get the sum of the array 'a' along axis=1
print(a.sum(axis = 1))

[ 6 17 14]
[10 13 14]


In [315]:
# Write a NumPy function to reverse the array 'a'
c=a[::-1]
print(c)
# Write a NumPy function to reverse the array 'a' along axis=0
print(a[:,::-1])

# Write a NumPy function to reverse the array 'a' along axis=1
print(a[::-1,:])

[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]


In [316]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [317]:
# Write a NumPy function to sort the array 'a'
print(np.sort(a))

# Write a NumPy function to sort the array 'a' along axis=0
print(np.sort(a,axis=0))

# Write a NumPy function to sort the array 'a' along axis=1
print(np.sort(a,axis=1))

# Write a NumPy function to sort the array 'a' in descending order along axis=0
f=np.sort(a,axis=0)
print(f[::-1,:])


[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [318]:
# Write a NumPy function to argsort the array along axis=0
print(a.argsort(axis=0))

# Write a NumPy function to argsort the array along axis=1
print(a.argsort(axis=1))


[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [319]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a,b),axis=0))

# Note: You can do the same function using stacking, discover and try that :)
print(np.concatenate((a,b),axis=1))

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]


In [320]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [321]:
 #Write a NumPy function to get the Number of dimensions
print(a.ndim)

# Write a NumPy function to get the Shape of the array
print(a.shape)

# Write a NumPy function to get the Size of the array
print(a.size)


2
(3, 3)
9


In [322]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print(a.reshape(1,9))

[[4 6 8 9 3 1 1 8 5]]


In [323]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this

#method 1
np.expand_dims(a,axis = 0)

#method 2
a[:,np.newaxis]

array([[[4, 6, 8]],

       [[9, 3, 1]],

       [[1, 8, 5]]])

In [324]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [325]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range

#indexing by integer
print("Row at index 1:", a[1])
print("Element at row 1, column 2:", a[1][2])

#by topule
print("Element at (2, 1):", a[2, 1])
print("Element at (0, 0):", a[0, 0])

#by slucing
print("First two rows:\n", a[0:2])

print("All rows, first two columns:\n", a[:, 0:2])


print("Last row:", a[-1])


Row at index 1: [0 3 1]
Element at row 1, column 2: 1
Element at (2, 1): 8
Element at (0, 0): 4
First two rows:
 [[4 6 0]
 [0 3 1]]
All rows, first two columns:
 [[4 6]
 [0 3]
 [1 8]]
Last row: [1 8 5]


In [326]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4) & (a%2==0)])

[6 8 5]
[6 8]


In [327]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [328]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
new = a.copy()
new = new + 1
print(new)


[[5 7 1]
 [1 4 2]
 [2 9 6]]


In [329]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

data = pd.read_csv('iris.data.txt', header=None)
print(data.head())
#iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Saving iris.data.txt to iris.data (2).txt
     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa


In [330]:
# Write a Pandas function to drop rows that contain a missing value
new_data = data.dropna()
new_data.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
print(new_data)
#print(new_data.columns)


     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [331]:
# Write a Pandas function to find the correlation between the first two columns.
correlation = new_data.iloc[:, [0, 1]].corr()
print(correlation)

              sepal_length  sepal_width
sepal_length      1.000000    -0.109369
sepal_width      -0.109369     1.000000


In [332]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print( new_data.iloc[:,2].mean())
print( new_data.iloc[:,2].median())
print( new_data.iloc[:,2].std())


3.758666666666666
4.35
1.7644204199522617


In [333]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
print(new_data.columns)
new_data['volume'] = (np.pi * new_data['petal_length'] * (new_data['sepal_length'] ** 2)) / 3
print(new_data.head())


Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
   sepal_length  sepal_width  petal_length  petal_width      species  \
0           5.1          3.5           1.4          0.2  Iris-setosa   
1           4.9          3.0           1.4          0.2  Iris-setosa   
2           4.7          3.2           1.3          0.2  Iris-setosa   
3           4.6          3.1           1.5          0.2  Iris-setosa   
4           5.0          3.6           1.4          0.2  Iris-setosa   

      volume  
0  38.132652  
1  35.200498  
2  30.072372  
3  33.238050  
4  36.651914  


## **Section B (2 Marks each)**

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [334]:

x = np.arange(4, dtype=np.int64)

ones_array = np.ones_like(x)

print(ones_array)
print(ones_array.dtype)


[1 1 1 1]
int64


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [335]:

x = np.arange(1, 10)

# Split sizes: 4, 2, 3
split_indices = [4, 6]

result = np.split(x, split_indices)

for arr in result:
    print(arr)


[1 2 3 4]
[5 6]
[7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [336]:

x = np.random.randint(0, 10, size=(2, 5))

print("Array x:")
print(x)
max_values = x.max(axis=1)
max_indices = x.argmax(axis=1)

min_values = x.min(axis=1)
min_indices = x.argmin(axis=1)

print("\nMaximum values along axis=1:", max_values)
print("Indices of maximum values:", max_indices)

print("\nMinimum values along axis=1:", min_values)
print("Indices of minimum values:", min_indices)


Array x:
[[1 4 6 4 4]
 [2 9 5 2 4]]

Maximum values along axis=1: [6 9]
Indices of maximum values: [2 1]

Minimum values along axis=1: [1 2]
Indices of minimum values: [0 0]


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [337]:
iris = np.genfromtxt( 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' , delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
df = pd.DataFrame(iris, columns=names)


Q4 Write a Pandas function to find the count of unique species.

In [338]:
print(df['species'].nunique())

3


Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
greater than equal to 5 –> ‘large’

In [339]:
# Convert numeric columns from bytes to float
for col in names[:-1]:  # exclude 'species'
    df[col] = df[col].astype(float)

# Define conditions
conditions = [
    df['petallength'] < 3,
    (df['petallength'] >= 3) & (df['petallength'] < 5),
    df['petallength'] >= 5
]

# Define the choices for each condition
choices = ['small', 'medium', 'large']
df['petallength_category'] = np.select(conditions, choices, default='unknown')
# Create a new column with the binned category



Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset


In [340]:
df['petallength'] = pd.to_numeric(df['petallength'], errors='coerce')

# Find the most frequent (mode) value in petallength
most_frequent_value = df['petallength'].mode()[0]

print("Most frequent petal length value is:", most_frequent_value)


Most frequent petal length value is: 1.5
