<a href="https://colab.research.google.com/github/VoKisnaHai1102/Frames-to-Fables/blob/main/Copy_of_Numpy_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [3]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [7]:
# Write a NumPy function to create an array with random values of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]

from numpy import random
x= np.random.rand(3,4)
print(x)
y = np.zeros((3,4))
print(y)
z = np.ones((3,4))
print(z)


[[0.09437878 0.4492464  0.60093256 0.06140388]
 [0.37434437 0.24687942 0.95011658 0.22975023]
 [0.18082834 0.6187859  0.45723859 0.99458631]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
def create_range_arange(start, stop, step):
    return np.arange(start, stop, step)

### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [33]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def operator(a, s, b):
    if s == '+':
        return np.add(a,b)
    elif s == '-':
        return np.subtract(a,b)
    elif s == '*':
        return np.multiply(a,b)
    elif s == '/':
        return np.divide(a,b)
    else:
        return "Invalid operator"

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
print(operator(a, '+', b))
print(operator(a, '-', b))
print(operator(a, '/', b))
print(operator(a, '*', b))





[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]


In [34]:
# Write a NumPy function to get the sum of the array 'a' along axis=0

# Write a NumPy function to get the sum of the array 'a' along axis=1
def sum_along_axis0(a):
    return np.sum(a, axis=0)

def sum_along_axis1(a):
    return np.sum(a, axis=1)


In [35]:
# Write a NumPy function to reverse the array 'a'

# Write a NumPy function to reverse the array 'a' along axis=0

# Write a NumPy function to reverse the array 'a' along axis=1

def reverse_array(a):
    return a[::-1]

def reverse_array_axis0(a):
    return np.flip(a, axis=0)

def reverse_array_axis1(a):
    return np.flip(a, axis=1)

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [37]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [36]:
# Write a NumPy function to sort the array 'a'

# Write a NumPy function to sort the array 'a' along axis=0

# Write a NumPy function to sort the array 'a' along axis=1

# Write a NumPy function to sort the array 'a' in descending order along axis=0

def sort_array(a):
    return np.sort(a, axis=None)

def sort_axis0(a):
    return np.sort(a, axis=0)

def sort_axis1(a):
    return np.sort(a, axis=1)

def sort_axis0_desc(a):
    return np.sort(a, axis=0)[::-1]


In [38]:
# Write a NumPy function to argsort the array along axis=0

# Write a NumPy function to argsort the array along axis=1

import numpy as np
def argsort_axis0(a):
    return np.argsort(a, axis=0)

def argsort_axis1(a):
    return np.argsort(a, axis=1)

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])

print(argsort_axis0(a))
print(argsort_axis1(a))




[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [39]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0

# Note: You can do the same function using stacking, discover and try that :)

def concatenate_arrays(a, b):
    return np.concatenate((a, b), axis=None)

def concatenate_arrays_axis0(a, b):
    return np.concatenate((a, b), axis=0)



### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [40]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [41]:
# Write a NumPy function to get the Number of dimensions

# Write a NumPy function to get the Shape of the array

# Write a NumPy function to get the Size of the array

def get_dimensions(a):
    return a.ndim

def get_shape(a):
    return a.shape

def get_size(a):
    return a.size


In [42]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)

def reshape_array(a):
    return a.reshape(1,9)


In [43]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this

def add_new_axis0(a):
    return np.expand_dims(a, axis=0)

def add_new_axis1(a):
    return np.expand_dims(a, axis=1)

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [44]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [45]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range

def indexing_and_slicing():
    a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

    print(a[1, 2])
    index = (2, 0)
    print(a[index])

    print(a[0:2, 1:3])

indexing_and_slicing()

1
1
[[6 0]
 [3 1]]


In [46]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2

def select_values_4():
    a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
    return a[a>4]
def select_values_4_and_2():
    a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
    return a[(a>4) & (a%2==0)]



### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [47]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [48]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1

def copy_plus1(a):

    # Make a copy of array 'a'
    b = a.copy()

    # Increment all elements by 1
    b += 1

    return b

a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
print(a)
print(copy_plus1(a))

[[4 6 0]
 [0 3 1]
 [1 8 5]]
[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [49]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [50]:
# Write a Pandas function to drop rows that contain a missing value.

import pandas as pd
import numpy as np


def drop_missing_rows():
  df = pd.DataFrame(iris_2d)
  df.dropna(inplace=True)
  return df

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

print(drop_missing_rows())


       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [7]:
# Write a Pandas function to find the correlation between the first two columns.
def correlation_first_two_columns():

    df = pd.DataFrame(iris_2d)
    correlation = df.iloc[:, 0].corr(df.iloc[:, 1])

    return correlation

print(correlation_first_two_columns())



-0.10936924995064937


In [9]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
def mean_median_std_column_3(a):
    df = pd.DataFrame(iris_2d)
    mean = df.iloc[:, 2].mean()
    median = df.iloc[:, 2].median()
    std = df.iloc[:, 2].std()
    if a == 'mean':
        return mean
    elif a == 'median':
        return median
    elif a == 'std':
        return std

print(mean_median_std_column_3('mean'))
print(mean_median_std_column_3('median'))
print(mean_median_std_column_3('std'))



3.758666666666666
4.35
1.7644204199522617


In [10]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

def add_volume_column(url):

  #This I Could not get which is length and which is width. I had to search online.
    df = pd.DataFrame(iris_2d, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

    volume = (np.pi * df['petal_length'] * (df['sepal_length'] ** 2)) / 3

    # Add the new column
    df['volume'] = volume

    return df

# Example usage
df_with_volume = add_volume_column(url)
print(df_with_volume.head())

   sepal_length  sepal_width  petal_length  petal_width     volume
0           5.1          3.5           1.4          0.2  38.132652
1           4.9          3.0           1.4          0.2  35.200498
2           4.7          3.2           1.3          0.2  30.072372
3           4.6          3.1           1.5          0.2  33.238050
4           5.0          3.6           1.4          0.2  36.651914


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [11]:
x = np.arange(4, dtype=np.int64)
ones_array = np.ones_like(x)

print(ones_array)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.






Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [12]:
from numpy import random

x = random.randint(0, 10, size=(2, 5))
print(x)

max_values = np.max(x, axis=1)
min_values = np.min(x, axis=1)

max_indices = np.argmax(x, axis=1)
min_indices = np.argmin(x, axis=1)

print(max_values, min_values, max_indices, min_indices)

[[9 0 1 5 4]
 [6 1 3 1 4]]
[9 6] [0 1] [0 0] [1 1]


### Pandas

Run the following load command and solve the following questions

In [13]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.




In [14]:
def unique_species():
    df = pd.DataFrame(iris, columns=names)
    species_counts = df['species'].value_counts()
    return species_counts

print(unique_species())

species
b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: count, dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [51]:
import pandas as pd
def new_array():
    df = pd.DataFrame(iris, columns=names)
    petal_length = df['petallength']
    new_array = []
    for i in petal_length:
      i = float(i) #forgot this step... was getting error for a long time.
      if i < 3:
            new_array.append('small')
      elif i >= 3 and i < 5:
            new_array.append('medium')
      else:
            new_array.append('large')
    return new_array


print(new_array())

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [26]:
def frequent_value():
    df = pd.DataFrame(iris, columns=names)
    petal_length = df['petallength']
    most_frequent_value = petal_length.mode()[0]#In this case it is not necessary to access the first element but in case of multiple modes, we need to access the first element only.
    return most_frequent_value

print(frequent_value())


b'1.5'
