Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
y = [1,2,3,4,5]
x = np.array(y)
print(x)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
print(b)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
a = np.random.rand(3,4)
print(a)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
b = np.zeros((3,4))
print(b)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
c = np.ones((3,4))
print(c)

[[0.49261223 0.81364294 0.001096   0.00847566]
 [0.6583588  0.89648381 0.24247128 0.36988796]
 [0.76933278 0.81459862 0.8919547  0.34155983]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
c = a + b
print(c)
d = a - b
print(d)
e = a * b
print(e)
f = a / b
print(f)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
x = np.sum(a, axis=0)
print(x)
# Write a NumPy function to get the sum of the array 'a' along axis=1
y = np.sum(a, axis=1)
print(y)

[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
z = np.flip(a)
print(z)

# Write a NumPy function to reverse the array 'a' along axis=0
y = np.flip(a, axis=0)
print(y)

# Write a NumPy function to reverse the array 'a' along axis=1
x = np.flip(a, axis=1)
print(x)


[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
x = np.sort(a)
print(x)

# Write a NumPy function to sort the array 'a' along axis=0
y = np.sort(a, axis=0)
print(y)

# Write a NumPy function to sort the array 'a' along axis=1
z = np.sort(a, axis=1)
print(z)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
p = np.flip(y, axis=0)
print(p)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
p = np.argsort(a, axis=0)
print(p)

# Write a NumPy function to argsort the array along axis=1
q = np.argsort(a, axis=1)
print(q)


[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
x = np.concatenate((a,b))
print(x)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
y = np.concatenate((a,b), axis=0)
print(y)

# Note: You can do the same function using stacking, discover and try that :)
z = np.vstack((a,b))
print(z)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
x = a.ndim
print(x)
# Write a NumPy function to get the Shape of the array
y = a.shape
print(y)
# Write a NumPy function to get the Size of the array
z = a.size
print(z)

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
x = a.reshape(1,9)
print(x)

[[4 6 8 9 3 1 1 8 5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
y = a[np.newaxis, :]
print(y)
p = y.shape
print(p)
# Note : Show atleast two different ways of doing this
z = a[:,np.newaxis]
print(z)
q = z.shape
print(q)

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
(1, 3, 3)
[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]
(3, 1, 3)


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
p = a[1]
print(p)
q = a[1,2]
print(q)
r = a[0:2,1]
print(r)

[0 3 1]
1
[6 3]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
x = a[a>4]
print(x)
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
y = a[(a>4) & (a%2==0)]
print(y)

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
x = a
x = x+1
print(x)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df = pd.DataFrame(iris_2d)
x = df.dropna()
print(x)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
x = df[0].corr(df[1])
print(x)

-0.10936924995064937


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
x = df[2].mean()
print(x)
y = df[2].median()
print(y)
z = df[2].std()
print(z)

3.758666666666666
4.35
1.7644204199522617


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

#What arre petellenghths and sepallengths in this case?


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
a = np.ones(shape=(x.shape), dtype=np.int64)
print(a)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
import numpy as np
x =np.array(range(1, 10, 1))
z = np.split(x,[4,6])
print(z)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import numpy as np
x = np.random.uniform(0,10,(2,5))
print(x)
y = np.max(x, axis=1)
a = np.argmax(x, axis=1)
print(a)
print(y)
z = np.min(x, axis=1)
b = np.argmin(x, axis=1)
print(b)
print(z)

[[4.42705609 7.72100729 4.95105559 9.46752508 9.96099312]
 [5.69063546 7.54176636 6.59290586 1.71013606 0.62608479]]
[4 1]
[9.96099312 7.54176636]
[0 4]
[4.42705609 0.62608479]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
import pandas as pd
df = pd.DataFrame(iris , columns = ['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])
df['species'].nunique()

3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
import pandas as pd
df = pd.DataFrame(iris_2d, columns = ['sepallength', 'sepalwidth', 'petallength', 'petalwidth'])
pd.cut(df['petallength'], bins= [-np.inf, 2, 5, np.inf], labels= ['short', 'medium', 'long'])

0       short
1       short
2       short
3       short
4       short
        ...  
145      long
146    medium
147      long
148      long
149      long
Name: petallength, Length: 150, dtype: category
Categories (3, object): ['short' < 'medium' < 'long']

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
x = df['petallength']
x.mode()

0    1.5
Name: petallength, dtype: float64