Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [56]:
import numpy as np

In [57]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr = np.array([1,2,3,4,5])
print(arr)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr2 = np.array([[1,2,3],[3,4,6],[7,8,9]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [3 4 6]
 [7 8 9]]


In [58]:
# Write a NumPy function to create an array with random values of shape [3,4]
x=np.random.randint(1000, size=(3,4))
print(x)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
y = np.zeros((3,4))
print( y)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
z = np.ones((3,4))
print(z)


[[868 145 466 980]
 [910 321 695 659]
 [774 657 474 733]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [59]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
num = np.linspace(0,100,5)
print(num)
# Hint : Use np.arange or np.linspace

[  0.  25.  50.  75. 100.]


### Basic array operations
- algebraic operations
- logical operations

In [60]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [61]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
add = a + b
sub = a - b
mul =a*b
div = a/b
print(add)
print(sub)
print(mul)
print(div)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [62]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
sum_a0 = np.sum(a,axis =0)
print(sum_a0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
sum_a1 = np.sum(a,axis = 1)
print(sum_a1)

[ 6 17 14]
[10 13 14]


In [63]:
# Write a NumPy function to reverse the array 'a'
rev = np.flip(a)
print(rev)

# Write a NumPy function to reverse the array 'a' along axis=0
rev_a0 = np.flip(a, axis = 0)
print(rev_a0)
# Write a NumPy function to reverse the array 'a' along axis=1
rev_a1 = np.flip(a, axis = 1)
print(rev_a1)


[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [64]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [65]:
# Write a NumPy function to sort the array 'a'
s = np.sort(a, axis = None).reshape((3,3))
print(s)
# Write a NumPy function to sort the array 'a' along axis=0
s0 = np.sort(a, axis = 0)
print(s0)
# Write a NumPy function to sort the array 'a' along axis=1
s1 = np.sort(a,axis = 1)
print(s1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
des_s0 = np.flip(s0, axis  = 0)
print(des_s0)

[[-4  1  1]
 [ 3  5  6]
 [ 8  8  9]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [66]:
# Write a NumPy function to argsort the array along axis=0
ars_0 = np.argsort(a, axis  =0)
print(ars_0)
# Write a NumPy function to argsort the array along axis=1
ars_1 = np.argsort(a, axis  =1)
print(ars_1)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [67]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
new = np.concatenate((a,b))
print(new)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
new_0 = np.concatenate((a,b),axis =0)
print(new_0)
# Note: You can do the same function using stacking, discover and try that :)
n = np.hstack((a,b))
print(n)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [68]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [69]:
# Write a NumPy function to get the Number of dimensions
dimensions = a.ndim
print("numebr of dimensions :",dimensions)
# Write a NumPy function to get the Shape of the array
shape  = a.shape
print("The shape of the array is :",shape)
# Write a NumPy function to get the Size of the array
size = a.size
print("The size of the array is :",size)

numebr of dimensions : 2
The shape of the array is : (3, 3)
The size of the array is : 9


In [70]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
New_arr = a.reshape((1,9))
print(New_arr)

[[4 6 8 9 3 1 1 8 5]]


In [71]:
# Write a NumPy function to add a new axis to the array 'a'
arrN = np.expand_dims(a,axis = 2)
print(arrN.shape)
arrN2 = a[np.newaxis,:,:]
print(arrN2.shape)
# Note : Show atleast two different ways of doing this


(3, 3, 1)
(1, 3, 3)


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [72]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [73]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
#integer
print("a[1][1] :",a[1][1])
#indexing by tuple
print("a[1,1] :",a[1,1])
#using range
print("a[:2,1:] :",a[:2,1:])

a[1][1] : 3
a[1,1] : 3
a[:2,1:] : [[6 0]
 [3 1]]


In [74]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print("for single condition: ")
print(a>4)
print(a[a>4])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print("\nfor multiple condition: ")
print((a>4) & (a%2 == 0))
print(a[(a>4) & (a%2 == 0)])

for single condition: 
[[False  True False]
 [False False False]
 [False  True  True]]
[6 8 5]

for multiple condition: 
[[False  True False]
 [False False False]
 [False  True False]]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [75]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [76]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
cpy = a.copy()
cpy = cpy + 1
print(cpy)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [77]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [78]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df = pd.DataFrame(iris_2d)
df_new = df.dropna()
print(df_new)


       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [79]:
# Write a Pandas function to find the correlation between the first two columns.
cor = df.iloc[:, 0].corr(df.iloc[:, 1])
print(cor)

-0.10936924995064937


In [80]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean3 = df.iloc[:,2].mean()
print(mean3)
med = df.iloc[:,2].median()
print(med)
sd = df.iloc[:,2].std()
print(sd)

3.758666666666666
4.35
1.7644204199522617


In [81]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
df = pd.DataFrame(iris_2d, columns = ['sepallength', 'sepalwidth', 'petallength', 'petalwidth'])
df['volume'] = df['petallength'] * 3.14 * df['sepallength'] * df['sepallength'] / 3
print(df)
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

     sepallength  sepalwidth  petallength  petalwidth      volume
0            5.1         3.5          1.4         0.2   38.113320
1            4.9         3.0          1.4         0.2   35.182653
2            4.7         3.2          1.3         0.2   30.057127
3            4.6         3.1          1.5         0.2   33.221200
4            5.0         3.6          1.4         0.2   36.633333
..           ...         ...          ...         ...         ...
145          6.7         3.0          5.2         2.3  244.321307
146          6.3         2.5          5.0         1.9  207.711000
147          6.5         3.0          5.2         2.0  229.952667
148          6.2         3.4          5.4         2.3  217.262880
149          5.9         3.0          5.1         1.8  185.815780

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [82]:
x = np.arange(4,dtype=np.int64)
y = np.ones_like(x)
print(y)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [83]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = np.split(x,[4,6])
print(y)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [84]:
x = np.random.uniform(low = 0, high = 10 ,size  =(2,5))
print(x)
max = np.max(x , axis =1)
min = np.min(x, axis =1 )
max_index = np.argmax(x,axis =1)
min_index = np.argmin(x,axis =1)
print("Max value + index: ")
print(max)
print(max_index)
print("Min value + index: ")
print(min)
print(min_index)

[[9.68999799 8.25539343 6.22844691 1.65141686 3.50025145]
 [6.96320594 6.09753941 7.23215186 5.41789903 2.91335146]]
Max value + index: 
[9.68999799 7.23215186]
[0 2]
Min value + index: 
[1.65141686 2.91335146]
[3 4]


### Pandas

Run the following load command and solve the following questions

In [85]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [86]:
df  = pd.DataFrame(iris,columns = names)
unique = df['species'].nunique()
print('Number of unique species: ', unique)
count = df['species'].value_counts()
print(count)

Number of unique species:  3
species
b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: count, dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [87]:
#df = pd.DataFrame(iris, columns = ['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])
df['petallength'] = df['petallength'].astype(float)
bins = [0, 3, 4.9, np.inf]
lab = ['small', 'medium', 'large']
pd.cut(df['petallength'], bins = bins, labels=lab )


0      small
1      small
2      small
3      small
4      small
       ...  
145    large
146    large
147    large
148    large
149    large
Name: petallength, Length: 150, dtype: category
Categories (3, object): ['small' < 'medium' < 'large']

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [88]:
most_frequent = df['petallength'].mode()[0]
print(most_frequent)

1.5
