Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [67]:
import numpy as np

In [68]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
list1 = [1, 2, 3, 4 , 5]
arr1 = np.array(list1)
print(arr1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2 = np.array(list2)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr1 = np.random.rand(3, 4)
print(arr1)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr2 = np.zeros((3, 4))
print(arr2)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr3 = np.ones((3, 4))
print(arr3)

[[0.22934863 0.65179917 0.81098509 0.80958639]
 [0.58962117 0.54355967 0.3642971  0.09961775]
 [0.20796095 0.35260862 0.59522154 0.23674373]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [70]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
arr = np.arange(0, 10, 2)
print(arr)
# Hint : Use np.arange or np.linspace

[0 2 4 6 8]


### Basic array operations
- algebraic operations
- logical operations

In [71]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [72]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [73]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
print(np.sum(a, axis=0))
# Write a NumPy function to get the sum of the array 'a' along axis=1
print(np.sum(a, axis=1))

[ 6 17 14]
[10 13 14]


In [74]:
# Write a NumPy function to reverse the array 'a'
print(np.flip(a))
# Write a NumPy function to reverse the array 'a' along axis=0
print(np.flip(a, axis=0))
# Write a NumPy function to reverse the array 'a' along axis=1
print(np.flip(a, axis=1))

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [75]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [76]:
# Write a NumPy function to sort the array 'a'
print(np.sort(a))  # i noted that if we write just sort not along any axis then it sort along axis = 1 by default
# Write a NumPy function to sort the array 'a' along axis=0
print(np.sort(a, axis=0))
# Write a NumPy function to sort the array 'a' along axis=1
print(np.sort(a, axis=1))
# Write a NumPy function to sort the array 'a' in descending order along axis=0
print(np.sort(a, axis=0)[::-1])

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [77]:
# Write a NumPy function to argsort the array along axis=0
print(np.argsort(a, axis=0))
# Write a NumPy function to argsort the array along axis=1
print(np.argsort(a, axis=1))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [78]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
print(np.concatenate((a, b)))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a, b), axis=0))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 1
print(np.concatenate((a, b), axis=1))                                           #here by default it choice axis = 0
# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [79]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [80]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)
# Write a NumPy function to get the Shape of the array
print(a.shape)
# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9


In [81]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print(a.reshape(1, 9))

[[4 6 8 9 3 1 1 8 5]]


In [82]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
print(a[np.newaxis, :])
print(a[:, np.newaxis])

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [83]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [84]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range

a.reshape(1,a.size)
a1 = a.ravel()    #My logic is to convert it into 1 dimensional vector then by loop i will index and slice
for i in range(len(a1)):
  print(f"at {i} value is {a1[i]}")

print(a[:, 1:3])
#indexing by a integer
print(a[0, 0])

#indexing by a tuple
print(a[(0, 1)])

at 0 value is 4
at 1 value is 6
at 2 value is 0
at 3 value is 0
at 4 value is 3
at 5 value is 1
at 6 value is 1
at 7 value is 8
at 8 value is 5
[[6 0]
 [3 1]
 [8 5]]
4
6


In [85]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4

def greater_4(a):
    return a[a > 4]

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def greater_divisible_4(a):
  return a[(a > 4) & (a % 2 == 0)]

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [86]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [87]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
a_copy = a.copy()
print(a_copy + 1)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [88]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [89]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df = pd.DataFrame(iris_2d)
df_new = df.dropna()
print(df_new)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [90]:
# Write a Pandas function to find the correlation between the first two columns.


In [91]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print(df[2].mean())
print(df[2].median())
print(df[2].std())

3.758666666666666
4.35
1.7644204199522617


In [92]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [93]:
x = np.arange(4, dtype=np.int64)
array = np.zeros_like(x)
print(array)

[0 0 0 0]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [94]:
x = np.arange(1,10)
print(x)
x1 = np.split(x,[4,6])
print(x1)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [95]:
x = np.random.randint(0, 10, size=(2, 5))
print(x)

print(np.max(x, axis=1))
print(np.min(x, axis=1))
print(np.argmax(x, axis=1))
print(np.argmin(x, axis=1))

[[8 8 3 8 6]
 [7 0 5 4 6]]
[8 7]
[3 0]
[0 0]
[2 1]


### Pandas

Run the following load command and solve the following questions

In [96]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [97]:
import pandas as pd
df1 = pd.DataFrame(iris)
df1.columns = names
print(df1['species'].value_counts())

species
b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: count, dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [98]:
def bin_petal_length(df):
    col_name = df.columns[2]

    bins = [0, 3, 5, np.inf]
    labels = ['small', 'medium', 'large']

    # new binned column
    df['petal_length_category'] = pd.cut(df[col_name], bins=bins, labels=labels, right=False)

    return df


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [99]:
def most_frequent_petal_length(df):
    col_name = df.columns[2]
    return df[col_name].mode().iloc[0]