Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [342]:
import numpy as np

In [343]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr1 = np.array([1, 2, 3, 4, 5])
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [344]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr1 = np.random.random((3,4))
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr2 = np.zeros((3, 4))
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr3 = np.ones((3, 4))

In [345]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
arr = np.arange(0,10,2)
# Hint : Use np.arange or np.linspace

### Basic array operations
- algebraic operations
- logical operations

In [346]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [347]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
add = np.add(a, b)
subtract = np.subtract(a, b)
multiply = np.multiply(a, b)
divide = np.divide(a, b)


In [348]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
sum0 = np.sum(a, axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
sum1 = np.sum(a, axis=1)

In [349]:
# Write a NumPy function to reverse the array 'a'
reverse = a[::-1]
# Write a NumPy function to reverse the array 'a' along axis=0
reverse0 = a[::-1, :]
# Write a NumPy function to reverse the array 'a' along axis=1
reverse1 = a[:, ::-1]

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [350]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [351]:
# Write a NumPy function to sort the array 'a'
sort = np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
sort0 = np.sort(a, axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
sort1 = np.sort(a, axis = 1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
sortd0 = np.sort(a, axis=0)[::-1]

In [352]:
# Write a NumPy function to argsort the array along axis=0
index0 = np.argsort(a, axis=0)
# Write a NumPy function to argsort the array along axis=1
index1 = np.argsort(a, axis=1)

In [353]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
ab = np.concatenate((a,b))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
ab0 = np.concatenate((a,b), axis=0)
# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [354]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [355]:
# Write a NumPy function to get the Number of dimensions
dim = arr.ndim
# Write a NumPy function to get the Shape of the array
shape = arr.shape
# Write a NumPy function to get the Size of the array
size = arr.size

In [356]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
reshape = a.reshape(1,9)

In [357]:
# Write a NumPy function to add a new axis to the array 'a'
newaxis1 = a[np.newaxis, :]

newaxis2 = np.expand_dims(a, axis=1)
# Note : Show atleast two different ways of doing this

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [358]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [359]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
n = a[1]
n1 = a[1, 2]
n2 = a[0:2]
# Show all three - indexing by a integer, indexing by a tuple, using range


In [360]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
idx = np.where(a>4)
arr = a[idx]
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
idx = np.where((a>4) & (a%2==0))
arr = a[idx]

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [361]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [362]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
arr = a.copy()
arr += 1
print(arr)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [363]:
import pandas as pd

In [364]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [365]:
# Write a Pandas function to drop rows that contain a missing value.
iris_2d = pd.DataFrame(iris_2d)
iris_2d = iris_2d.dropna()

In [366]:
# Write a Pandas function to find the correlation between the first two columns.
corr = iris_2d[0].corr(iris_2d[1])

In [367]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean = iris_2d[2].mean()
median = iris_2d[2].median()
std = iris_2d[2].std()

In [368]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

volume = (np.pi * iris_2d[2] * iris_2d[0]**2) / 3
iris_2d['volume'] = volume

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [369]:
x = np.arange(4, dtype=np.int64)
ones = np.ones_like(x)

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [370]:
x = np.arange(1,10)
a, b, c = np.split(x, [4, 6])

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [371]:
x = np.random.randint(0,10, size= (2,5))
max_value = np.max(x)
max_index = np.argmax(x)
min_value = np.min(x)
min_index = np.argmin(x)

### Pandas

Run the following load command and solve the following questions

In [372]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [373]:
iris_df = pd.DataFrame(iris, columns=names)
count = iris_df['species'].nunique()
print(count)

3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [374]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth')
iris_2d = pd.DataFrame(iris_2d, columns=names)
def assign_bin(petallength):
  if petallength < 3:
    return 'small'
  elif petallength >= 3 and petallength < 5:
    return 'medium'
  else:
    return 'large'

iris_2d['bin'] = iris_2d['petallength'].apply(assign_bin)




Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [387]:
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
df = pd.DataFrame(iris, columns=names)
count = df['petallength'].value_counts().index[0]
count


b'1.5'