Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
ran=np.random.rand(3,4)
zeros=np.zeros((3,4))
ones=np.ones((3,4))
print(ran)
print(zeros)
print(ones)

[[0.2740189  0.83451941 0.23037112 0.33408153]
 [0.01244484 0.28804699 0.05499968 0.22953288]
 [0.31877441 0.5398656  0.01067785 0.1313648 ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
range=np.arange(0,17,4)
print(range)

[ 0  4  8 12 16]


### Basic array operations
- algebraic operations
- logical operations

In [7]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [9]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [10]:
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[ 6 17 14]
[10 13 14]


In [13]:
print(np.flip(a))
print(np.flip(a,axis=0))
print(np.flip(a,axis=1))

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [14]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [15]:
print(np.sort(a))
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))
print(np.sort(a,axis=0)[::-1])

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [16]:
print(np.argsort(a,axis=0))
print(np.argsort(a,axis=1))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [19]:
print(np.concatenate((a,b)))
print(np.concatenate((a,b),axis=0))
print(np.stack((a,b),axis=0))

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[[-4  6  8]
  [ 9  3  1]
  [ 1  8  5]]

 [[11 16 18]
  [90 37 81]
  [61 48 75]]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [20]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [21]:
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 3)
9


In [23]:
print(np.reshape(a,(1,9)))

[[4 6 8 9 3 1 1 8 5]]


In [30]:
print(a[np.newaxis,:])
print(np.expand_dims(a,axis=0))

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [32]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [44]:
print(a[0,0])
print(a[(0,0)])
print(a[np.arange(0,2),np.arange(0,2)])

4
4
[4 3]


In [50]:
print(a[a>4])
print(a[(a>4)&(a%2==0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [51]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [52]:
b=np.copy(a)
b=b+1
print(b)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [53]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [64]:
import pandas as pd
db=pd.DataFrame(data=iris_2d,columns=['sepal length','sepal width','petal length','petal width'])
db.dropna(inplace=True)
print(db)

     sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [66]:
print(db['sepal length'].corr(db['sepal width']))

-0.10936924995064937


In [68]:
print(db['petal width'].mean())
print(db['petal width'].median())
print(db['petal width'].std())

1.1986666666666668
1.3
0.7631607417008414


In [70]:
db['volume']=np.pi*(db['sepal length']**2)*db['petal length']
print(db)

     sepal length  sepal width  petal length  petal width      volume
0             5.1          3.5           1.4          0.2  114.397955
1             4.9          3.0           1.4          0.2  105.601495
2             4.7          3.2           1.3          0.2   90.217116
3             4.6          3.1           1.5          0.2   99.714151
4             5.0          3.6           1.4          0.2  109.955743
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3  733.335690
146           6.3          2.5           5.0          1.9  623.449062
147           6.5          3.0           5.2          2.0  690.207906
148           6.2          3.4           5.4          2.3  652.119237
149           5.9          3.0           5.1          1.8  557.730085

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [71]:
x = np.arange(4, dtype=np.int64)
y=np.ones(x.shape,dtype=x.dtype)
print(y)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [74]:
x=[1,2,3,4,5,6,7,8,9]
print(np.split(x,[4,6]))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [79]:
x=np.random.rand(2,5)*10
print(x)
print(np.max(x,axis=1))
print(np.argmax(x,axis=1))
print(np.min(x,axis=1))
print(np.argmin(x,axis=1))

[[3.27948799 5.45464913 2.6483047  0.33275101 1.22065964]
 [6.56493361 3.2359947  6.82825092 9.19042703 0.6346853 ]]
[5.45464913 9.19042703]
[1 3]
[0.33275101 0.6346853 ]
[3 4]


### Pandas

Run the following load command and solve the following questions

In [80]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [84]:
df=pd.DataFrame(data=iris,columns=names)
print(df['species'].nunique())

3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [92]:
df['petallength']=pd.to_numeric(df['petallength'])
df['petallength']=pd.cut(df['petallength'], bins=[0,3,5,1000], labels=['small', 'medium', 'large'])
print(df)

    sepallength sepalwidth petallength petalwidth            species
0        b'5.1'     b'3.5'       small     b'0.2'     b'Iris-setosa'
1        b'4.9'     b'3.0'       small     b'0.2'     b'Iris-setosa'
2        b'4.7'     b'3.2'       small     b'0.2'     b'Iris-setosa'
3        b'4.6'     b'3.1'       small     b'0.2'     b'Iris-setosa'
4        b'5.0'     b'3.6'       small     b'0.2'     b'Iris-setosa'
..          ...        ...         ...        ...                ...
145      b'6.7'     b'3.0'       large     b'2.3'  b'Iris-virginica'
146      b'6.3'     b'2.5'      medium     b'1.9'  b'Iris-virginica'
147      b'6.5'     b'3.0'       large     b'2.0'  b'Iris-virginica'
148      b'6.2'     b'3.4'       large     b'2.3'  b'Iris-virginica'
149      b'5.9'     b'3.0'       large     b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [86]:
print(df['petallength'].mode())

0    b'1.5'
Name: petallength, dtype: object
