Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it

#Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

pika = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(pika)

In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]


In [ ]:
from numpy import random
pika = random.randint(10,size = (3,4))
print(pika)
print()
fun = random.randint(1,size = (3,4))
print(fun)
print()
arr = random.choice([1],size =(3,4))
print(arr)

In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace

In [ ]:
arr = np.arange(2,20,4)
print(arr)

### Basic array operations
- algebraic operations
- logical operations

In [3]:
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'


In [ ]:
c = a+b
print(c)
print()
d = a-b
print(d)
print()
e = a*b
print(e)
print()
f=a/b
print(f)

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0

# Write a NumPy function to get the sum of the array 'a' along axis=1


In [9]:
arr1 = np.sum(a,axis = 0)
print(arr1)
arr2 = np.sum(a,axis =1)
print(arr2)

[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'

# Write a NumPy function to reverse the array 'a' along axis=0

# Write a NumPy function to reverse the array 'a' along axis=1


In [ ]:
arr = np.flip(a)
print(arr)
print()
arr1 = np.flip(a,axis=0)
print(arr1)
print()
arr2 = np.flip(a,axis=1)
print(arr2)

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'

# Write a NumPy function to sort the array 'a' along axis=0

# Write a NumPy function to sort the array 'a' along axis=1

# Write a NumPy function to sort the array 'a' in descending order along axis=0


In [ ]:
print(np.sort(a))
print()
print(np.sort(a,axis=0))
print()
print(np.sort(a,axis = 1))
print()
arr = np.sort(a,axis=0)
arr_new = np.flip(arr,axis=0)
print(arr_new)

In [ ]:
# Write a NumPy function to argsort the array along axis=0

# Write a NumPy function to argsort the array along axis=1


In [ ]:
pika = np.argsort(a,axis =0)
print(pika)
print()
pika1 = np.argsort(a,axis =1)
print(pika1)

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0

# Note: You can do the same function using stacking, discover and try that :)


In [ ]:
c = np.concatenate((a,b))
print(c)
print()
d = np.concatenate((a,b),axis = 0)
print(d)

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [26]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions

# Write a NumPy function to get the Shape of the array

# Write a NumPy function to get the Size of the array


In [ ]:
print(a.ndim)
print(a.shape)
print(a.size)

In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)


In [ ]:
a.reshape(-1)

In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this


In [29]:
fun = a[:,np.newaxis]
fun1 = a[:,None]

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [44]:
fun1=np.take(a,1,axis=0)
print(fun1)
fun2=a.item((1,2))
print(fun2)
fun3=a[0:2]
print(fun3)

[9 3 1]
1
[[4 6 8]
 [9 3 1]]


In [45]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2


In [46]:
c1=a[a>4]
print(c1)
c2=a[(a>4)&(a%2==0)]
print(c2)

[6 8 9 8 5]
[6 8 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [30]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1


In [33]:
b = a
#print(b)
b=b+1
print(b)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [6]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [18]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df = pd.read_csv(url)
#print(df)
pika = df.dropna()
print(pika)

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]


In [11]:
# Write a Pandas function to find the correlation between the first two columns.
fun = df.iloc[:,0].corr(df.iloc[:,1])
print(fun)

-0.10378414795681824


In [16]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean = df.iloc[:,2].mean()
median = df.iloc[:,2].median()
std = df.iloc[:,2].std()
print(mean)
print(median)
print(std)

3.774496644295302
4.4
1.7596511617753423


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

In [ ]:
df['volume'] = (3.14*df.iloc[:,2]*df.iloc[:,0]**2)/3
print(df)

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [34]:
x = np.arange(4,dtype=np.int64)
y = x+1-x
print(y)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [35]:
x = [1,2,3,4,5,6,7,8,9]
pika = np.array_split(x,[4,6])
print(pika)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import numpy as np
from numpy import random
arr = random.randint(10,size=(2,5))
print(arr)
max = np.max(arr,axis=1)
print(max)
min = np.min(arr,axis=1)
print(min)
i1 = np.argmax(arr,axis=1)
i2 = np.argmin(arr,axis=1)
print(i1)
print(i2)

### Pandas

Run the following load command and solve the following questions

In [40]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [41]:
df = pd.read_csv(url)
num = df.iloc[:,4].nunique()
print(num)

3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [43]:
import numpy as np
conditions = [
              df.iloc[:,2]<=3,
              (df.iloc[:,2]>3)&(df.iloc[:,2]<5),
              df.iloc[:,2]>=5
]
choices = ['small','medium','large']
df['petalsize'] = np.select(conditions,choices,default='unknown')
print(df)

     5.1  3.5  1.4  0.2     Iris-setosa petalsize
0    4.9  3.0  1.4  0.2     Iris-setosa     small
1    4.7  3.2  1.3  0.2     Iris-setosa     small
2    4.6  3.1  1.5  0.2     Iris-setosa     small
3    5.0  3.6  1.4  0.2     Iris-setosa     small
4    5.4  3.9  1.7  0.4     Iris-setosa     small
..   ...  ...  ...  ...             ...       ...
144  6.7  3.0  5.2  2.3  Iris-virginica     large
145  6.3  2.5  5.0  1.9  Iris-virginica     large
146  6.5  3.0  5.2  2.0  Iris-virginica     large
147  6.2  3.4  5.4  2.3  Iris-virginica     large
148  5.9  3.0  5.1  1.8  Iris-virginica     large

[149 rows x 6 columns]


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [35]:
x = df.iloc[:,2].mode()[0]
print(x)

1.5
