Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
list1=([1,2,3,4,5])
arr= np.array(list1)
print(arr)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
list2=([[2,4,6],[1,3,5],[1,4,7]])
arr1=np.array(list2)
print(arr1)

[1 2 3 4 5]
[[2 4 6]
 [1 3 5]
 [1 4 7]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr_random=np.random.rand(3,4)
print(arr_random)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
a=np.full((3,4),0)
print(a)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
b=np.full((3,4),1)
print(b)

[[0.0528763  0.29115589 0.16846232 0.93702131]
 [0.04352523 0.88352139 0.94468219 0.8178828 ]
 [0.44105509 0.77429555 0.82073656 0.27038047]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
x=np.sum(a,axis=0)
print(x)
# Write a NumPy function to get the sum of the array 'a' along axis=1
y=np.sum(a,axis=1)
print(y)

[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
z=a[::-1]
print(z)
# Write a NumPy function to reverse the array 'a' along axis=0
q=a[::-1, :]
print(q)
# Write a NumPy function to reverse the array 'a' along axis=1
w=a[:, ::-1]
print(w)

[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
a_sort=np.sort(a)
print(a_sort)
# Write a NumPy function to sort the array 'a' along axis=0
a0=np.sort(a,axis=0)
print(a0)
# Write a NumPy function to sort the array 'a' along axis=1
a1=np.sort(a,axis=1)
print(a1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
ad=np.sort(a,axis=0)[::-1]
print(ad)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
s=np.argsort(a, axis=0)
print(s)
# Write a NumPy function to argsort the array along axis=1
t=np.argsort(a, axis=1)
print(t)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
ab=np.concatenate((a,b))
print(ab)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
ab0=np.concatenate((a,b),axis=0)
print(ab0)
# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
print(np.ndim(a))
# Write a NumPy function to get the Shape of the array
print(np.shape(a))
# Write a NumPy function to get the Size of the array
print(np.size(a))

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
np.reshape(a,(1,9))

array([[4, 6, 8, 9, 3, 1, 1, 8, 5]])

In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
f=a[np.newaxis]
print(f.shape)
g=np.expand_dims(a, axis=1)
print(g.shape)

(1, 3, 3)
(3, 1, 3)


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
#Indexing by an integer
print(a[1])
#2.Indexing by a tuple
print(a[2,0])
#3.Using a range
print(a[0:2, 1:2])

[0 3 1]
1
[[6]
 [3]]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4) & (a%2==0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b=a.copy()
b=b+1
print(b)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df = pd.DataFrame(iris_2d, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
df_cleaned=df.dropna()
print(df_cleaned.head())

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
df['sepal_length'].corr(df['sepal_width'])

np.float64(-0.10936924995064937)

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
m=df['petal_length'].mean()
print(m)
n=df['petal_length'].median()
print(n)
s=df['petal_length'].std()
print(s)

3.758666666666666
4.35
1.7644204199522617


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
df['volume'] = (np.pi * df['petal_length'] * df['sepal_length']**2) / 3

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

> Add blockquote



In [ ]:
x = np.arange(4, dtype=np.int64)
ones = np.ones_like(x)
print(ones)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.arange(1,10)
a, b, c = np.split(x, [4, 6])
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6]
[7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.randint(0, 10, size=(2, 5))
print("x:\n", x)
max = np.max(x, axis=1)
max_indice= np.argmax(x, axis=1)
min = np.min(x, axis=1)
min_indice= np.argmin(x, axis=1)
print("Max value:", max)
print("Max indice:", max_indice)
print("Min value:", min)
print("Min indice:", min_indice)

x:
 [[3 5 2 4 8]
 [1 1 6 5 8]]
Max value: [8 8]
Max indice: [4 4]
Min value: [2 1]
Min indice: [2 0]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
df = pd.DataFrame(iris, columns=names)
df['species'].value_counts()

species
b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: count, dtype: int64

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
categories = pd.cut(petal_length,
                        bins=[-np.inf, 3, 5, np.inf],
                        labels=['small', 'medium', 'large'])
categories.to_numpy()

array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'mediu

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
petal_length = pd.to_numeric(df.iloc[:, 2], errors='coerce')
petal_length.mode().iloc[0]

np.float64(1.5)