Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [2]:
import numpy as np

In [3]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
a=[1,2,3,4,5]
b=np.array(a)
print(f"1D Array: {b}")

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
print(f"2D Array:\n {b}")

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Write a NumPy function to create an array with random values of shape [3,4]
a=np.random.rand(3,4)
print(f"Array of random values: \n {a} \n")

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
a=np.zeros((3,4))
print(f"Array initialized as zeros:\n {a} \n")

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
a=np.ones((3,4))
print(f"Array initialized as ones: \n {a} \n")

Array of random values: 
 [[5.80313298e-01 3.84221696e-01 1.71731612e-02 2.35030285e-04]
 [6.38319063e-02 2.07225125e-01 1.15593169e-01 5.92584421e-01]
 [6.71473258e-02 4.36468202e-01 9.31298829e-02 8.08426126e-01]] 

Array initialized as zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Array initialized as ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 



In [5]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
a=np.linspace(0,1,5)
print(f"Array containing a range of evenly spaced intervals: \n {a} \n")
# Hint : Use np.arange or np.linspace

Array containing a range of evenly spaced intervals: 
 [0.   0.25 0.5  0.75 1.  ] 



### Basic array operations
- algebraic operations
- logical operations

In [6]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [7]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
add=np.add(a,b)
sub=np.subtract(a,b)
mul=np.multiply(a,b)
div=np.divide(a,b)
print(f"Addition: \n {add} \n")
print(f"Subtraction: \n {sub} \n")
print(f"Multiplication: \n {mul} \n")
print(f"Division: \n {div} \n")

Addition: 
 [[ 7 22 26]
 [99 40 82]
 [62 56 80]] 

Subtraction: 
 [[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]] 

Multiplication: 
 [[-44  96 144]
 [810 111  81]
 [ 61 384 375]] 

Division: 
 [[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]] 



In [8]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
add=np.sum(a,axis=0)
print(f"Sum along axis=0: \n {add} \n")
# Write a NumPy function to get the sum of the array 'a' along axis=1
add_2=np.sum(a,axis=1)
print(f"Sum along axis=1: \n {add_2} \n")

Sum along axis=0: 
 [ 6 17 14] 

Sum along axis=1: 
 [10 13 14] 



In [9]:
# Write a NumPy function to reverse the array 'a'
rev=np.flip(a)
print(f"Reversed array: \n {rev} \n")
# Write a NumPy function to reverse the array 'a' along axis=0
rev0=np.flip(a,axis=0)
print(f"Reversed array along axis=0: \n {rev0} \n")
# Write a NumPy function to reverse the array 'a' along axis=1
rev1=np.flip(a,axis=1)
print(f"Reversed array along axis=1: \n {rev1} \n")

Reversed array: 
 [[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]] 

Reversed array along axis=0: 
 [[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]] 

Reversed array along axis=1: 
 [[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]] 



### Sorting and concatenation
- sort arrays
- join multiple arrays


In [10]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [11]:
# Write a NumPy function to sort the array 'a'
s=np.sort(a)
print(f"Sorted array: \n {s} \n")
# Write a NumPy function to sort the array 'a' along axis=0
s0=np.sort(a,axis=0)
print(f"Sorted array along axis=0: \n {s0} \n")
# Write a NumPy function to sort the array 'a' along axis=1
s1=np.sort(a,axis=1)
print(f"Sorted array along axis=1: \n {s1} \n")
# Write a NumPy function to sort the array 'a' in descending order along axis=0
s_dec0=np.sort(a,axis=0)[::-1]
print(f"Sorted array in descending order along axis=0: \n {s_dec0} \n")

Sorted array: 
 [[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]] 

Sorted array along axis=0: 
 [[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]] 

Sorted array along axis=1: 
 [[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]] 

Sorted array in descending order along axis=0: 
 [[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]] 



In [12]:
# Write a NumPy function to argsort the array along axis=0
args0=np.argsort(a,axis=0)
print(f"Sorted array along axis=0: \n {args0} \n")
# Write a NumPy function to argsort the array along axis=1
args1=np.argsort(a,axis=1)
print(f"Sorted array along axis=1: \n {args1} \n")

Sorted array along axis=0: 
 [[0 1 1]
 [2 0 2]
 [1 2 0]] 

Sorted array along axis=1: 
 [[0 1 2]
 [2 1 0]
 [0 2 1]] 



In [13]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
c=np.concatenate((a,b))
print(f"Concatenated array: \n {c} \n")
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
d=np.concatenate((a,b),axis=0)
print(f"Concatenated array along axis=0: \n {d} \n")
# Note: You can do the same function using stacking, discover and try that :)
e=np.stack((a,b),axis=0)
print(f"Concatenated array along axis=0 using stack: \n {e} \n")

Concatenated array: 
 [[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]] 

Concatenated array along axis=0: 
 [[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]] 

Concatenated array along axis=0 using stack: 
 [[[-4  6  8]
  [ 9  3  1]
  [ 1  8  5]]

 [[11 16 18]
  [90 37 81]
  [61 48 75]]] 



### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [14]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [15]:
# Write a NumPy function to get the Number of dimensions
dim=np.ndim(a)
print(f"Number of dimensions: \n {dim} \n")
# Write a NumPy function to get the Shape of the array
shp=np.shape(a)
print(f"Shape of the array: \n {shp} \n")
# Write a NumPy function to get the Size of the array
siz=np.size(a)
print(f"Size of the array: \n {siz} \n")

Number of dimensions: 
 2 

Shape of the array: 
 (3, 3) 

Size of the array: 
 9 



In [16]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
reshaped_a=np.reshape(a,(1,9))
print(f"Reshaped array: \n {reshaped_a} \n")

Reshaped array: 
 [[4 6 8 9 3 1 1 8 5]] 



In [17]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
shp=np.shape(a)
print(f"Shape of the array: \n {shp} \n")
b=np.expand_dims(a,axis=0)
bshape=np.shape(b)
print(f"New shape by expand_dims: \n {bshape} \n")
c=np.newaxis
c=a[np.newaxis, :]
cshape=np.shape(c)
print(f"New shape by new_axis: \n {cshape} \n")

Shape of the array: 
 (3, 3) 

New shape by expand_dims: 
 (1, 3, 3) 

New shape by new_axis: 
 (1, 3, 3) 



### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [29]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [38]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
print("Indexing by integer:\n", a[1:],"\n")

print("Indexing by tuple:\n",a[(1,2)],"\n")

print("Indexing by range:\n",a[:,1:3],"\n")


Indexing by integer:
 [[0 3 1]
 [1 8 5]] 

Indexing by tuple:
 1 

Indexing by range:
 [[6 0]
 [3 1]
 [8 5]] 



In [42]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print("Values >4:\n ",a[np.where(a>4)],"\n")
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print("Values >4 & divisible by 2:\n",a[np.where((a>4) & (a%2==0))],"\n")

Values >4:
  [6 8 5] 

Values >4 & divisible by 2:
 [6 8] 



### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [43]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [45]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b=a+1
print(f"Original array: \n {a} \n")
print(f"Original array with each number increased by 1: \n {b} \n")

Original array: 
 [[4 6 0]
 [0 3 1]
 [1 8 5]] 

Original array with each number increased by 1: 
 [[5 7 1]
 [1 4 2]
 [2 9 6]] 



## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [46]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [49]:
import pandas as pd

In [51]:
# Write a Pandas function to drop rows that contain a missing value.
df=pd.DataFrame(iris_2d)
df.dropna(axis=0)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [56]:
# Write a Pandas function to find the correlation between the first two columns.
corr_matrix=df.corr()
print(corr_matrix.loc[0,1])

-0.10936924995064931


In [57]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean=df[2].mean()
median=df[2].median()
std=df[2].std()
print(f"Mean: {mean}\nMedian: {median}\nStandard Deviation: {std}")

Mean: 3.758666666666666
Median: 4.35
Standard Deviation: 1.7644204199522617


In [58]:
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [60]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

sepal=df[0]
petal=df[2]
volume=(np.pi*petal*sepal**2)/3
df[4]=volume
df.head()

0    1    2    3          4
0  5.1  3.5  1.4  0.2  38.132652
1  4.9  3.0  1.4  0.2  35.200498
2  4.7  3.2  1.3  0.2  30.072372
3  4.6  3.1  1.5  0.2  33.238050
4  5.0  3.6  1.4  0.2  36.651914

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [61]:
x=np.arange(4,dtype=np.int64)
shp=np.shape(x)
ones=np.ones(shp)
print(ones)

[1. 1. 1. 1.]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [63]:
x=np.arange(1,10)
a,b,c=np.split(x,[4,6])
print(a,b,c)

[1 2 3 4] [5 6] [7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [66]:
x=np.random.randint(0,10,size=(2,5))
max_val=np.max(x,axis=1)
min_val=np.min(x,axis=1)
print("Maximum value= ",max_val,"\n","Minimum value= ",min_val)

Maximum value=  [7 9] 
 Minimum value=  [0 4]


### Pandas

Run the following load command and solve the following questions

In [67]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [71]:
df=pd.DataFrame(iris)
df.head()

0       1       2       3               4
0  b'5.1'  b'3.5'  b'1.4'  b'0.2'  b'Iris-setosa'
1  b'4.9'  b'3.0'  b'1.4'  b'0.2'  b'Iris-setosa'
2  b'4.7'  b'3.2'  b'1.3'  b'0.2'  b'Iris-setosa'
3  b'4.6'  b'3.1'  b'1.5'  b'0.2'  b'Iris-setosa'
4  b'5.0'  b'3.6'  b'1.4'  b'0.2'  b'Iris-setosa'

In [72]:
print(df[4].unique())

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [77]:
df[2] = pd.to_numeric(df[2])  #to convert all values to numbers since i was getting an error since some values were in bytes
labels=['small','medium','large']
bins=[0,3,5,float('inf')]
df['petal_length_bin'] = pd.cut(df[2], bins=bins, labels=labels)
df.head()

0       1    2       3               4 petal_length_bin
0  b'5.1'  b'3.5'  1.4  b'0.2'  b'Iris-setosa'            small
1  b'4.9'  b'3.0'  1.4  b'0.2'  b'Iris-setosa'            small
2  b'4.7'  b'3.2'  1.3  b'0.2'  b'Iris-setosa'            small
3  b'4.6'  b'3.1'  1.5  b'0.2'  b'Iris-setosa'            small
4  b'5.0'  b'3.6'  1.4  b'0.2'  b'Iris-setosa'            small

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [81]:
most_frequent = df[2].mode()
print("Most frequent petal length: ", most_frequent.iloc[0])

Most frequent petal length:  1.5
