Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [1]:
import numpy as np

In [2]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
array1_list = [1,2,3,4,5]
array1 = np.array(array1_list)
print(array1)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
array2_list = [1,2,3,4,5,6,7,8,9]
array2 = np.array(array2_list).reshape(3,3)
print(array2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Write a NumPy function to create an array with random values of shape [3,4]
array3 = np.random.rand(3,4)
print(array3)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
array4 = np.zeros((3,4))
print(array4)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
array5 = np.ones((3,4))
print(array5)

[[0.99331438 0.98370585 0.29208084 0.75264786]
 [0.07056882 0.4734889  0.63351694 0.53760227]
 [0.88183891 0.17866212 0.0141033  0.08921359]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
array6 = np.linspace(1,10,5)
print(array6)
# Hint : Use np.arange or np.linspace

[ 1.    3.25  5.5   7.75 10.  ]


### Basic array operations
- algebraic operations
- logical operations

In [5]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [6]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def fun1(a,b):
  if a.shape == b.shape:
    print("a+b = \n", a+b)
    print("a-b = \n", a-b)
    print("a*b = \n", a*b)
    print("a/b = \n", a/b)
  else:
    print("Arrays are of different shapes")

fun1(a,b)

a+b = 
 [[ 7 22 26]
 [99 40 82]
 [62 56 80]]
a-b = 
 [[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
a*b = 
 [[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
a/b = 
 [[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [7]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
def fun2(a):
  return np.sum(a, axis=0)
print(fun2(a))
# Write a NumPy function to get the sum of the array 'a' along axis=1
def fun3(a):
  return np.sum(a, axis=1)
print(fun3(a))

[ 6 17 14]
[10 13 14]


In [8]:
# Write a NumPy function to reverse the array 'a'
array7 = a[::-1, ::-1]
print(array7)

# Write a NumPy function to reverse the array 'a' along axis=0
array8 = a[::-1]
print(array8)

# Write a NumPy function to reverse the array 'a' along axis=1
array9 = a[:, ::-1]
print(array9)

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [9]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [10]:
# Write a NumPy function to sort the array 'a'
array10 = np.sort(a)
print(array10)
# Write a NumPy function to sort the array 'a' along axis=0
array11 = np.sort(a, axis =0)
print(array11)
# Write a NumPy function to sort the array 'a' along axis=1
array12 = np.sort(a, axis =1)
print(array12)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
array13 = np.sort(a, axis=0)[::-1]
print(array13)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [11]:
# Write a NumPy function to argsort the array along axis=0
print(np.argsort(a,axis=0))
# Write a NumPy function to argsort the array along axis=1
print(np.argsort(a,axis=1))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [12]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def fun4(a,b,axis):
  print(np.concatenate((a,b), axis=axis))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
fun4(a,b,0)
# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [13]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [14]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)
# Write a NumPy function to get the Shape of the array
print(a.shape)
# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9


In [15]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
a.reshape(1,9)

array([[4, 6, 8, 9, 3, 1, 1, 8, 5]])

In [16]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this

array14 = a[:, np.newaxis]
array15 = np.expand_dims(a, axis=1)
print(array14,"\n", array15)

[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]] 
 [[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [17]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [18]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
print("Indexing by a integer",a[0])
print("Indexing by a tuple",a[0,1])
print(a[:4])

Indexing by a integer [4 6 0]
Indexing by a tuple 6
[[4 6 0]
 [0 3 1]
 [1 8 5]]


In [19]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a > 4) & (a % 2 == 0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [20]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [21]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
c = np.copy(a)
print(c+1)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [22]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [23]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df = pd.DataFrame(iris_2d)
df.dropna()

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [24]:
# Write a Pandas function to find the correlation between the first two columns.
print(df[0].corr(df[1]))

-0.10936924995064937


In [25]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

In [26]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print("Mean: ",df[2].mean(),"\nMedian: ",df[2].median(), "\nStd: ", df[2].std())

Mean:  3.758666666666666 
Median:  4.35 
Std:  1.7644204199522617


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [27]:
x1 = np.arange(4, dtype=np.int64)
array16 = np.ones_like(x1)
print(array16)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [28]:
x2 = [1,2,3,4,5,6,7,8,9]
array17, array18, array19 = x2[:4], x2[4:6], x2[6:9]
print(array17, array18, array19)

[1, 2, 3, 4] [5, 6] [7, 8, 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [29]:
x = np.random.randint(0,10, size=(2,5))

max_vals = np.max(x, axis=1)
min_vals = np.min(x, axis=1)
max_indices = np.argmax(x, axis=1)
min_indices = np.argmin(x, axis=1)

print("Array x:\n", x)
print("Max values along axis 1:", max_vals)
print("Indices of max values:", max_indices)
print("Min values along axis 1:", min_vals)
print("Indices of min values:", min_indices)

Array x:
 [[5 9 2 1 0]
 [3 4 4 6 0]]
Max values along axis 1: [9 6]
Indices of max values: [1 3]
Min values along axis 1: [0 0]
Indices of min values: [4 4]


### Pandas

Run the following load command and solve the following questions

In [30]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [31]:
df1 = pd.DataFrame(iris)
df1 = df1.applymap(lambda x: x.decode('utf-8') if isinstance(x, bytes) else x)
df1[4].nunique()

<ipython-input-31-a1065ed115e2>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1 = df1.applymap(lambda x: x.decode('utf-8') if isinstance(x, bytes) else x)


3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [32]:
df1[2] = pd.to_numeric(df1[2], errors='coerce')

conditions = [
      df1[2] < 3,
      df1[2].between(3, 5, inclusive='left'),
      df1[2] >= 5
  ]
choices = ['small', 'medium', 'large']
df1['petal_size'] = np.select(conditions, choices, default='unknown')

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [33]:
df1.iloc[:,2].mode().iloc[0]

np.float64(1.5)