Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [1]:
import numpy as np

In [2]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr = np.array([1,2,3,4,5])
print(arr)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Write a NumPy function to create an array with random values of shape [3,4]
def random_arr():
  return np.random.rand(3,4)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def zero_arr():
  return np.zeros((3,4))

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
def ones_arr():
  return np.ones((3,4))

print (random_arr(), zero_arr(), ones_arr())

[[0.57395816 0.51599254 0.81712249 0.23411096]
 [0.46050149 0.57095452 0.0133481  0.80803272]
 [0.17358353 0.21608427 0.09833463 0.21378592]] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
def even_arr():
  return np.arange(0,11,2)
print (even_arr())

[ 0  2  4  6  8 10]


### Basic array operations
- algebraic operations
- logical operations

In [7]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [8]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def math(a,b,op):
  if op == '+':
    return a+b
  elif op == '-':
    return a-b
  elif op == '*':
    return a*b
  elif op == '/':
    return a/b

print(math(a,b,'*'))

[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]


In [9]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
def sum0(a):
  return np.sum(a,axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
def sum1(a):
  return np.sum(a,axis=1)

print(sum0(a), sum1(a))

[ 6 17 14] [10 13 14]


In [10]:
# Write a NumPy function to reverse the array 'a'
def reverse(a):
  return np.flip(a)

# Write a NumPy function to reverse the array 'a' along axis=0
def reverse0(a):
  return np.flip(a,axis=0)

# Write a NumPy function to reverse the array 'a' along axis=1
def reverse1(a):
  return np.flip(a,axis=1)

print (reverse(a), reverse0(a), reverse1(a))

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]] [[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]] [[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [11]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [12]:
# Write a NumPy function to sort the array 'a'
def sort(a):
  m, n = a.shape
  flat_a = a.flatten()
  sorted_a = np.sort(flat_a)
  return sorted_a.reshape(m, n)


# Write a NumPy function to sort the array 'a' along axis=0
def sort0(a):
  return np.sort(a,axis=0)

# Write a NumPy function to sort the array 'a' along axis=1
def sort1(a):
  return np.sort(a,axis=1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
def des_sort(a):
  arr = a*(-1)
  return np.sort(arr,axis=0)*(-1)

print(sort(a), sort0(a), sort1(a), des_sort(a))

[[-4  1  1]
 [ 3  5  6]
 [ 8  8  9]] [[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]] [[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]] [[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [14]:
# Write a NumPy function to argsort the array along axis=0
def argsort0(a):
  return np.argsort(a,axis=0)

# Write a NumPy function to argsort the array along axis=1
def argsort1(a):
  return np.argsort(a,axis=1)

print(argsort0(a), argsort1(a))

[[0 1 1]
 [2 0 2]
 [1 2 0]] [[0 1 2]
 [2 1 0]
 [0 2 1]]


In [15]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concat(a,b):
  return np.concatenate((a,b))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concat0(a,b):
  return np.concatenate((a,b),axis=0)

def stack0(a,b):
  return np.vstack((a,b))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 1
def concat1(a,b):
  return np.concatenate((a,b),axis=1)

def stack1(a,b):
  return np.hstack((a,b))

# Note: You can do the same function using stacking, discover and try that :)
print (concat(a,b), concat0(a,b), stack0(a,b), concat1(a,b), stack1(a,b))

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]] [[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]] [[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]] [[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]] [[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [16]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [17]:
# Write a NumPy function to get the Number of dimensions
def ndim(a):
  return a.ndim

# Write a NumPy function to get the Shape of the array
def shape(a):
  return a.shape

# Write a NumPy function to get the Size of the array
def size(a):
  return a.size

print (ndim(a), shape(a), size(a))

2 (3, 3) 9


In [18]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape(a):
  return a.reshape(1,9)
print (reshape(a))

[[4 6 8 9 3 1 1 8 5]]


In [19]:
# Write a NumPy function to add a new axis to the array 'a'
def newaxis(a):
  return a[:,:,np.newaxis]
print (newaxis(a))

# Note : Show atleast two different ways of doing this
def expand_dims(a):
  return np.expand_dims(a, axis=2)
print (expand_dims(a))

[[[4]
  [6]
  [8]]

 [[9]
  [3]
  [1]]

 [[1]
  [8]
  [5]]]
[[[4]
  [6]
  [8]]

 [[9]
  [3]
  [1]]

 [[1]
  [8]
  [5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [20]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [21]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
def index(arr):
  print(arr[0])
  print(arr[1, 2])
  print(arr[0:1], 2)

In [22]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
def select(arr):
  return arr[arr > 4]

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def select1 (arr):
  return arr[(arr>4) & (arr%2 == 0)]

print (select(a), select1(a))

[6 8 5] [6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [23]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [24]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def copy(arr):
  arr_copy = arr.copy()
  arr_copy += 1
  return arr_copy

print(copy(a))

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [25]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [26]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd

def drop_missing(df, ):
  df = pd.DataFrame(df)
  return df.dropna()

drop_missing(iris_2d)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [27]:
# Write a Pandas function to find the correlation between the first two columns.
def findcorr(df):
  df = pd.DataFrame(df)
  return df.iloc[:, 0].corr(df.iloc[:, 1])

findcorr(iris_2d)

np.float64(-0.10936924995064937)

In [28]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
def describe(df):
  df = pd.DataFrame(df)
  return df.iloc[:, 2].mean(), df.iloc[:, 2].median(), df.iloc[:, 2].std()

describe(iris_2d)

(np.float64(3.758666666666666), 4.35, 1.7644204199522617)

In [29]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
def add_volume(df, columns):
  df = pd.DataFrame(df, columns = columns)
  df['volume'] = (np.pi * df.loc[:, 'petallength'] * df.loc[:, 'sepal_length']**2)/3
  return df

columns = ['sepal_length', 'sepalwidth', 'petallength', 'petalwidth']
add_volume(iris_2d, columns)
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

sepal_length  sepalwidth  petallength  petalwidth      volume
0             5.1         3.5          1.4         0.2   38.132652
1             4.9         3.0          1.4         0.2   35.200498
2             4.7         3.2          1.3         0.2   30.072372
3             4.6         3.1          1.5         0.2   33.238050
4             5.0         3.6          1.4         0.2   36.651914
..            ...         ...          ...         ...         ...
145           6.7         3.0          5.2         2.3  244.445230
146           6.3         2.5          5.0         1.9  207.816354
147           6.5         3.0          5.2         2.0  230.069302
148           6.2         3.4          5.4         2.3  217.373079
149           5.9         3.0          5.1         1.8  185.910028

[150 rows x 5 columns]

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [30]:
x = np.arange(4, dtype=np.int64)
a = np.ones_like(x)
print(a)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [31]:
x = np.arange(1, 10)
a, b, c = np.split(x, [4,6])
print(a, b, c)

[1 2 3 4] [5 6] [7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [32]:
x = np.random.randint(0, 10, size=(2, 5))
print(x)
max_vals = np.max(x, axis=1)
max_index = np.argmax(x, axis=1)
min_vals = np.min(x, axis=1)
min_index = np.argmin(x, axis=1)
print(max_vals, max_index, min_vals, min_index)

[[3 2 5 4 6]
 [0 2 8 3 6]]
[6 8] [4 2] [2 0] [1 0]


### Pandas

Run the following load command and solve the following questions

In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [34]:
def unique_species(df):
  df = pd.DataFrame(df, columns=names)
  return df['species'].nunique()
unique_species(iris)

3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [35]:
def bin(df):
  df = pd.DataFrame(df, columns=names)
  df['petallength'] = df['petallength'].astype(float)
  bins = [0, 3, 5, float('inf')]
  labels = ['small', 'medium', 'large']
  return pd.cut(df['petallength'], bins=bins, labels=labels)

bin(iris)

0       small
1       small
2       small
3       small
4       small
        ...  
145     large
146    medium
147     large
148     large
149     large
Name: petallength, Length: 150, dtype: category
Categories (3, object): ['small' < 'medium' < 'large']

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [36]:
def most_freq_petal_length(df):
  df = pd.DataFrame(df, columns=names)
  df['petallength'] = df['petallength'].astype(float)
  print(df['petallength'].mode()[0])

most_freq_petal_length(iris)

1.5
