Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [1]:
import numpy as np

In [3]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
set_1=np.array([1,2,3,4,5])
print(set_1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
set_2=np.array([[[1,2,3],[3,4,5],[6,7,8]]])
# set_2 = np.arange(1, 10).reshape(3, 3)

print(set_2)

[1 2 3 4 5]
[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


In [10]:
# Write a NumPy function to create an array with random values of shape [3,4]
# set_3=np.random.random((3,4))
set_3=np.random.randint(1,100,(3,4))
print(set_3)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
set_4=np.zeros((3,4))
print(set_4)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
set_5=np.ones((3,4))
print(set_5)

[[91 52 72 34]
 [40 41 59 29]
 [17 94 59 25]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals

set_6=np.arange(1,13,2)  #giving step ,its a ex
print(set_6)

set_7=np.linspace(1,14,6) #giving total number of elements,not ex
print(set_7)

# Hint : Use np.arange or np.linspace

[ 1  3  5  7  9 11]
[ 1.   3.6  6.2  8.8 11.4 14. ]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [18]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

add=np.add(a,b)
sub=np.subtract(a,b)
mult=np.multiply(a,b)
div=np.divide(a,b)

print (f"add\n{add}\n\n sub\n{sub}\n\n mult\n{mult}\n\n div\n{div}\n")


add
[[ 7 22 26]
 [99 40 82]
 [62 56 80]]

 sub
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]

 mult
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]

 div
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]



In [20]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
sum_0=np.sum(a,axis=0)
print(sum_0)

# Write a NumPy function to get the sum of the array 'a' along axis=1
sum_1=np.sum(a,axis=1)
print(sum_1)


[ 6 17 14]
[10 13 14]


In [22]:
# Write a NumPy function to reverse the array 'a'
a_1=np.flip(a)
a_2=np.flip(a, axis=0)
a_3=np.flip(a, axis=1)
print(a)
print (a_1)
print (a_2)
print (a_3)

# Write a NumPy function to reverse the array 'a' along axis=0

# Write a NumPy function to reverse the array 'a' along axis=1


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]
[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
a_sort=a.sort()

# Write a NumPy function to sort the array 'a' along axis=0
a_sort_1=a.sort(axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
a_sort_2=a.sort(axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
a_sort_1=a.sort(axis=0)[::-1, :]

In [ ]:
# Write a NumPy function to argsort the array along axis=0
a_ar_1=a.argsort(axis=0)

# Write a NumPy function to argsort the array along axis=1
a_ar_1=a.argsort(axis=1)

In [24]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
A_B=np.concatenate((a,b))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
A_B_0=np.concatenate((a,b),axis=0)
A_B_1=np.concatenate((a,b),axis=1)
stacked_0 = np.stack((a, b), axis=0)
stacked_0 = np.stack((a, b), axis=0)  #similarly vstack and  hstack



# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
a_d=a.ndim
# Write a NumPy function to get the Shape of the array
a_sh=a.shape

# Write a NumPy function to get the Size of the array
a_si=a.size

In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
a_re=a.reshape((1,9))

In [25]:
# Write a NumPy function to add a new axis to the array 'a'
a_newaxis_2 = np.expand_dims(a, axis=1)
a_newaxis_1 = a[:, np.newaxis]
# Note : Show atleast two different ways of doing this


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
row_1 = a[1]
element = a[1, 2]
slice_rows = a[0:2, 1:3]
# Show all three - indexing by a integer, indexing by a tuple, using range


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
result = a[a > 4]

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
result = a[(a > 4) & (a%2 ==0)]

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [28]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
B=np.copy(a)
c=np.ones((3,3))
print(B+c)

[[5. 7. 1.]
 [1. 4. 2.]
 [2. 9. 6.]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [29]:
A=np.ones((1,4),dtype=np.int64)

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9])
x_1=x[0:3]
x_2=x[3:6]
x_3=x[6:9]

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [30]:
x=np.random.randint(0,10,(2,5))
y=x.max(axis=1)
y_1=x.min(axis=1)
y_w=x.argmax(axis=1)
y_q=x.argmax(axis=1)

### Pandas

Run the following load command and solve the following questions

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [33]:
species = iris[:, 4]
uni=np.unique(species, return_counts=True)

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [34]:

petal = iris[:, 2].astype(float)

petal_category = np.where(petal < 3, 'small',
                 np.where(petal < 5, 'medium', 'large'))

print(petal_category)

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'large' 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'medium' 'large' 'large' 'large'
 'large' 'large' 'large' 'large' 'large' 'large' 'large' '

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [35]:

values, counts = np.unique(petal, return_counts=True)
mostfreq = values[np.argmax(counts)]