Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [3]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr1=np.array([1,2,3,4,5])
print(arr1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr1=np.random.rand(3,4)
print(arr1)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr2=np.zeros((3,4))
print(arr2)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
np.ones((3,4))


[[0.15754565 0.5668643  0.66796366 0.89544718]
 [0.60052021 0.91155983 0.58605491 0.79849849]
 [0.34438293 0.86913726 0.30327629 0.16330301]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
np.arange(0,10,2)
# Hint : Use np.arange or np.linspace

array([0, 2, 4, 6, 8])

### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)


array([[-0.36363636,  0.375     ,  0.44444444],
       [ 0.1       ,  0.08108108,  0.01234568],
       [ 0.01639344,  0.16666667,  0.06666667]])

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
np.sum(a,axis=0)

# Write a NumPy function to get the sum of the array 'a' along axis=1
np.sum(a,axis=1)


In [ ]:
# Write a NumPy function to reverse the array 'a'
np.flip(a)

# Write a NumPy function to reverse the array 'a' along axis=0
np.flip(a,axis=0)

# Write a NumPy function to reverse the array 'a' along axis=1
np.flip(a,axis=1)


array([[ 8,  6, -4],
       [ 1,  3,  9],
       [ 5,  8,  1]])

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
np.sort(a)

# Write a NumPy function to sort the array 'a' along axis=0
np.sort(a,axis=0)

# Write a NumPy function to sort the array 'a' along axis=1
np.sort(a,axis=1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
np.sort(a,axis=0)[::-1]


array([[ 9,  8,  8],
       [ 1,  6,  5],
       [-4,  3,  1]])

In [ ]:
# Write a NumPy function to argsort the array along axis=0
np.argsort(a,axis=0)

# Write a NumPy function to argsort the array along axis=1
np.argsort(a,axis=1)


array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
np.concatenate((a,b))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
np.concatenate((a,b),axis=0)

# Note: You can do the same function using stacking, discover and try that :)



### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
np.dim(a)

# Write a NumPy function to get the Shape of the array
np.shape(a)

# Write a NumPy function to get the Size of the array
np.size(a)


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
np.reshape(a,(1,9))


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
np.expand_dims(a,axis=0)
np.reshape(a,(1,-1))




array([[-4,  6,  8,  9,  3,  1,  1,  8,  5]])

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by
arr1=np.copy(a)
np.add(arr1,1)


array([[5, 7, 1],
       [1, 4, 2],
       [2, 9, 6]])

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df=pd.DataFrame(iris_2d)
print(df)
df.dropna()



       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
print(df.iloc[:, 0].corr(df.iloc[:, 1]))


-0.10936924995064937


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print(df.iloc[:, 2].mean())
print(df.iloc[:, 2].median())
print(df.iloc[:, 2].std())


3.758666666666666
4.35
1.7644204199522617


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
df['volume']=(np.pi*df.iloc[:, 2]*df.iloc[:, 0]**2)/3
print(df)

# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

       0    1    2    3      volume
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
import numpy as np

x = np.arange(4, dtype=np.int64)
ones = np.ones_like(x)

print(ones)
print(ones.dtype)


[1 1 1 1]
int64


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.arange(1, 10)
a, b, c = x[:4], x[4:6], x[6:]
print("a:", a)
print("b:", b)
print("c:", c)


a: [1 2 3 4]
b: [5 6]
c: [7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.randint(0, 10, size=(2, 5))
print(x)
max_val = np.max(x, axis=1)
min_val = np.min(x, axis=1)

[[7 5 5 4 1]
 [0 0 3 8 9]]


### Pandas

Run the following load command and solve the following questions

In [4]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [12]:
pd.Series(df.iloc[:, -1]).nunique()


3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [13]:
import pandas as pd
import numpy as np

def bin_petal_length(df):
    bins = [0, 3, 5, np.inf]
    labels = ['small', 'medium', 'large']

    return pd.cut(df.iloc[:, 2].astype(float), bins=bins, labels=labels, right=False).astype(str)


print(bin_petal_length(df))

0      small
1      small
2      small
3      small
4      small
       ...  
145    large
146    large
147    large
148    large
149    large
Name: petallength, Length: 150, dtype: object


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [14]:
pd.Series(df.iloc[:, 2].astype(float)).mode()


0    1.5
Name: petallength, dtype: float64