Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [59]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it

In [ ]:
list1=[1,2,3,4,5]
array1=np.array(list1)
print(array1)
list2=[[1,2,3],[4,5,6],[7,8,9]]
array2=np.array(list2)
print(array2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]


In [ ]:
array3=np.random.rand(3,4)
array4=np.zeros((3,4))
array5=np.ones((3,4))
print(array3)
print(array4)
print(array5)

[[0.97930967 0.36451773 0.13216425 0.56208812]
 [0.59821828 0.11630769 0.46899922 0.21541801]
 [0.72713062 0.64899723 0.16282869 0.62120903]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace

In [ ]:
array6=np.arange(0,20,4)
print(array6)

[ 0  4  8 12 16]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'


In [ ]:
add=a+b
sub=a-b
mul=a*b
div=a/b
print(sum)
print(sub)
print(mul)
print(div)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0

# Write a NumPy function to get the sum of the array 'a' along axis=1


In [ ]:
sum0=np.sum(a,axis=0)
sum1=np.sum(a,axis=1)
print(sum0)
print(sum1)

[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'

# Write a NumPy function to reverse the array 'a' along axis=0

# Write a NumPy function to reverse the array 'a' along axis=1


In [ ]:
rev0=np.flip(a,axis=0)
rev1=np.flip(a,axis=1)
print(rev0)
print(rev1)

[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'

# Write a NumPy function to sort the array 'a' along axis=0

# Write a NumPy function to sort the array 'a' along axis=1

# Write a NumPy function to sort the array 'a' in descending order along axis=0


In [ ]:
sort0=np.sort(a,axis=0)
sort1=np.sort(a,axis=1)
sort2=np.sort(a,axis=0)[::-1]
print(sort0)
print(sort1)
print(sort2)

[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0

# Write a NumPy function to argsort the array along axis=1


In [ ]:
argsort0=np.argsort(a,axis=0)
argsort1=np.argsort(a,axis=1)
print(argsort0)
print(argsort1)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0

# Note: You can do the same function using stacking, discover and try that :)


In [ ]:
cat0=np.concatenate((a,b),axis=0)
print(cat0)
cat02=np.vstack((a,b))
print(cat02)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions

# Write a NumPy function to get the Shape of the array

# Write a NumPy function to get the Size of the array


In [ ]:
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)

In [40]:
newarray=a.reshape(-1)
print(newarray)

[4 6 8 9 3 1 1 8 5]


In [43]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this

In [42]:
newaxis1 = a[:,np.newaxis]
print(newaxis1)
newaxis2 = a[:,None]
print(newaxis2)

[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]
[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [71]:
array1=np.take(a,1,axis=0)
print (array1)
array2=a.item((2,2))
print(array2)
array3=a[0:2]
print(array3)

[0 3 1]
5
[[4 6 0]
 [0 3 1]]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2


In [73]:
g4=a[a>4]
print(g4)
g42=a[(a>4)&(a%2==0)]
print(g42)

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [44]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [45]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1


In [46]:
copy=a
copy=copy+1
print(copy)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [47]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [48]:
# Write a Pandas function to drop rows that contain a missing value.


In [49]:
import pandas as pd
data = pd.read_csv(url)
dropped = data.dropna()
print(dropped)

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]


In [50]:
# Write a Pandas function to find the correlation between the first two columns.


In [51]:
correlation= data.iloc[:,0].corr(data.iloc[:,1])
print(correlation)

-0.10378414795681824


In [70]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.

In [53]:
mean = data.iloc[:,2].mean()
median = data.iloc[:,2].median()
std = data.iloc[:,2].std()
print(mean)
print(median)
print(std)

3.774496644295302
4.4
1.7596511617753423


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

In [54]:
data['volume'] = (3.14*data.iloc[:,2]*data.iloc[:,0]**2)/3
print(data)

     5.1  3.5  1.4  0.2     Iris-setosa      volume
0    4.9  3.0  1.4  0.2     Iris-setosa   35.182653
1    4.7  3.2  1.3  0.2     Iris-setosa   30.057127
2    4.6  3.1  1.5  0.2     Iris-setosa   33.221200
3    5.0  3.6  1.4  0.2     Iris-setosa   36.633333
4    5.4  3.9  1.7  0.4     Iris-setosa   51.885360
..   ...  ...  ...  ...             ...         ...
144  6.7  3.0  5.2  2.3  Iris-virginica  244.321307
145  6.3  2.5  5.0  1.9  Iris-virginica  207.711000
146  6.5  3.0  5.2  2.0  Iris-virginica  229.952667
147  6.2  3.4  5.4  2.3  Iris-virginica  217.262880
148  5.9  3.0  5.1  1.8  Iris-virginica  185.815780

[149 rows x 6 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [55]:
x = np.arange(4,dtype=np.int64)
ones = x+1-x
print(ones)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [56]:
x = [1,2,3,4,5,6,7,8,9]
arrays = np.array_split(x,[4,6])
print(arrays)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [61]:
from numpy import random

In [65]:
array1 = random.randint(10,size=(2,5))
print(array1)
max = np.max(array1,axis=1)
print(max)
min = np.min(array1,axis=1)
print(min)
first = np.argmax(array1,axis=1)
second= np.argmin(array1,axis=1)
print(first)
print(second)

[[1 6 6 4 4]
 [4 1 3 3 0]]
[6 4]
[1 0]
[1 0]
[0 4]


### Pandas

Run the following load command and solve the following questions

In [66]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [67]:
data2 = pd.read_csv(url)
n = data2.iloc[:,4].nunique()
print(n)

3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [68]:
import numpy as np
conditions = [
              data2.iloc[:,2]<=3,
              (data2.iloc[:,2]>3)&(data2.iloc[:,2]<5),
              data2.iloc[:,2]>=5
]
abc = ['small','medium','large']
data2['petalsize'] = np.select(conditions,abc,default='unknown')
print(data2)

     5.1  3.5  1.4  0.2     Iris-setosa petalsize
0    4.9  3.0  1.4  0.2     Iris-setosa     small
1    4.7  3.2  1.3  0.2     Iris-setosa     small
2    4.6  3.1  1.5  0.2     Iris-setosa     small
3    5.0  3.6  1.4  0.2     Iris-setosa     small
4    5.4  3.9  1.7  0.4     Iris-setosa     small
..   ...  ...  ...  ...             ...       ...
144  6.7  3.0  5.2  2.3  Iris-virginica     large
145  6.3  2.5  5.0  1.9  Iris-virginica     large
146  6.5  3.0  5.2  2.0  Iris-virginica     large
147  6.2  3.4  5.4  2.3  Iris-virginica     large
148  5.9  3.0  5.1  1.8  Iris-virginica     large

[149 rows x 6 columns]


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [69]:
mode_l = data2.iloc[:,2].mode()[0]
print(mode_l)

1.5
