Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [84]:
import numpy as np

In [85]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
x = np.array([1,2,3,4,5])
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [86]:
# Write a NumPy function to create an array with random values of shape [3,4]
np.random.random((3, 4))
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
np.zeros((3, 4))
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
np.arange(0, 777, 7)

array([  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
        91,  98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175,
       182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266,
       273, 280, 287, 294, 301, 308, 315, 322, 329, 336, 343, 350, 357,
       364, 371, 378, 385, 392, 399, 406, 413, 420, 427, 434, 441, 448,
       455, 462, 469, 476, 483, 490, 497, 504, 511, 518, 525, 532, 539,
       546, 553, 560, 567, 574, 581, 588, 595, 602, 609, 616, 623, 630,
       637, 644, 651, 658, 665, 672, 679, 686, 693, 700, 707, 714, 721,
       728, 735, 742, 749, 756, 763, 770])

### Basic array operations
- algebraic operations
- logical operations

In [88]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [89]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
c = np.add(a, b)
cc = np.subtract(a, b)
ccc = np.multiply(a, b)
cccc = np.divide(a, b)

In [90]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
cs = np.sum(a, axis = 0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
rs = np.sum(a, axis = 1)

In [91]:
# Write a NumPy function to reverse the array 'a'
na = np.flip(a)
# Write a NumPy function to reverse the array 'a' along axis=0
naa = np.flip(a, axis = 0)
# Write a NumPy function to reverse the array 'a' along axis=1
naaa = np.flip(a, axis = 1)

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [92]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [93]:
# Write a NumPy function to sort the array 'a'
sorted = np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
c_sorted = np.sort(a, axis = 0)
# Write a NumPy function to sort the array 'a' along axis=1
r_sorted = np.sort(a, axis = 1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
rd_sorted = np.sort(a, axis = 0)[::-1]
# Write a NumPy function to sort the array 'a' in descending order along axis=1
rc_sorted = np.sort(a, axis = 1)[::-1]

In [94]:
# Write a NumPy function to argsort the array along axis=0
np.argsort(a, axis = 0)
# Write a NumPy function to argsort the array along axis=1
np.argsort(a, axis = 1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [95]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
np.concatenate((a, b))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
np.concatenate((a, b), axis = 0)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 1
np.concatenate((a, b), axis = 1)
# Note: You can do the same function using stacking, discover and try that :)
## For axis = 0 or vertically stacking
np.vstack((a, b))
## For axis = 1 or horizontally stacking
np.hstack((a, b))

array([[-4,  6,  8, 11, 16, 18],
       [ 9,  3,  1, 90, 37, 81],
       [ 1,  8,  5, 61, 48, 75]])

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [96]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [97]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)
# Write a NumPy function to get the Shape of the array
print(a.shape)
# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9


In [98]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
a.reshape((1,9))

array([[4, 6, 8, 9, 3, 1, 1, 8, 5]])

In [99]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
a = a[:, :, np.newaxis]
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
a = a.reshape((a.shape[0], a.shape[0], 1))
a.ndim

3

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [100]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [101]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
print(a[1][1])
print(a[1,1])
print(a[0:2, 0:2])

3
3
[[4 6]
 [0 3]]


In [102]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a > 4])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a > 4) & (a % 2 == 0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [103]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [104]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b = np.copy(a)
print(b + 1)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [105]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [106]:
import pandas as pd
# Write a Pandas function to drop rows that contain a missing value.
df = pd.DataFrame(iris_2d)
df.dropna()

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [107]:
# Write a Pandas function to find the correlation between the first two columns.
df[[0,1]].corr()

0         1
0  1.000000 -0.109369
1 -0.109369  1.000000

In [108]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print(df[2].mean())
print(df[2].median())
print(df[2].std())

3.758666666666666
4.35
1.7644204199522617


In [109]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
volume = (np.pi * df[2] * (df[0] ** 2)) / 3
pd.concat([df, volume], axis = 1)
df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [110]:
x = np.arange(4, dtype=np.int64)
np.ones(x.shape, dtype = x.dtype)

array([1, 1, 1, 1])

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [111]:
x = np.arange(1, 10)
p = x[0 : 4]
q = x[4 : 6]
r = x[6 : 9]
print(p)
print(q)
print(r)

[1 2 3 4]
[5 6]
[7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [112]:
x = np.random.uniform(0, 10, (2, 5))
print(x)
print(np.max(x, axis = 1))
print(np.argmax(x, axis = 1))
print(np.min(x, axis = 1))
print(np.argmin(x, axis = 1))

[[4.70255894 7.64163448 2.32456581 4.37760745 8.22068305]
 [9.61769018 9.10900383 9.99678549 9.74681481 3.48557017]]
[8.22068305 9.99678549]
[4 2]
[2.32456581 3.48557017]
[2 4]


### Pandas

Run the following load command and solve the following questions

In [113]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [114]:
df = pd.DataFrame(iris)
print(df[4].nunique())
print(df[4].value_counts())

3
4
b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: count, dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [115]:
bins = [0, 3, 5, np.inf]
labels = ['small', 'medium', 'large']
df[2] = pd.to_numeric(df[2])

df[2] = pd.cut(df[2], bins=bins, labels=labels, right = False)
df

0       1      2       3                  4
0    b'5.1'  b'3.5'  small  b'0.2'     b'Iris-setosa'
1    b'4.9'  b'3.0'  small  b'0.2'     b'Iris-setosa'
2    b'4.7'  b'3.2'  small  b'0.2'     b'Iris-setosa'
3    b'4.6'  b'3.1'  small  b'0.2'     b'Iris-setosa'
4    b'5.0'  b'3.6'  small  b'0.2'     b'Iris-setosa'
..      ...     ...    ...     ...                ...
145  b'6.7'  b'3.0'  large  b'2.3'  b'Iris-virginica'
146  b'6.3'  b'2.5'  large  b'1.9'  b'Iris-virginica'
147  b'6.5'  b'3.0'  large  b'2.0'  b'Iris-virginica'
148  b'6.2'  b'3.4'  large  b'2.3'  b'Iris-virginica'
149  b'5.9'  b'3.0'  large  b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [116]:
df = pd.DataFrame(iris)
df[2] = pd.to_numeric(df[2])
df[2].mode()

0    1.5
Name: 2, dtype: float64