Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [51]:
import numpy as np

In [50]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr=np.arange(1,6)
print(arr)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr2=np.arange(1,10).reshape(3,3)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr3=np.random.randint(0,100,12).reshape(3,4)
print(arr3)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
zer=np.zeros((3,4))
print(zer)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
ones=zer.copy()
ones[:,:]=1
print(ones)

[[95 45  6 54]
 [79 10 37  5]
 [ 3 12 98 89]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
qq=np.arange(1,18,2)
print(qq)
# Hint : Use np.arange or np.linspace

[ 1  3  5  7  9 11 13 15 17]


### Basic array operations
- algebraic operations
- logical operations

In [16]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [20]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
su=np.add(a,b)
print(su)
subt=np.subtract(a,b)
print(subt)
mul=np.multiply(a,b)
print(mul)
div=np.divide(a,b)
print(div)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0

# Write a NumPy function to get the sum of the array 'a' along axis=1
def sum(a):
   return np.sum(a, axis=0)

def sum1(a):
   return np.sum(a, axis=1)

In [ ]:
# Write a NumPy function to reverse the array 'a'
def reverse_array(a):

  return np.flip(a)

# Write a NumPy function to reverse the array 'a' along axis=0
def reverse_array_0(a):

  return np.flip(a,axis=0)
# Write a NumPy function to reverse the array 'a' along axis=1
def reverse_array_1(a):

  return np.flip(a,axis=1)


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [38]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [46]:
# Write a NumPy function to sort the array 'a'
def sort(a):
  np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
def sort_0(a):
  np.sort(a,axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
def sort_1(a):
  np.sort(a,axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
def revsort(a):
  aww=np.argsort(a)
  fina=np.flip(aww)
  rev=a[fina]
  return rev
((sort(a)))
print(a)
(sort_0(a))
print(a)
(sort_1(a))
print(a)
revsort(a)
print(a)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
def argsot(a):
  return np.argsort(a,axis=0)
# Write a NumPy function to argsort the array along axis=1
def argsot1(a):
  return np.argsort(a,axis=1)
argsot(a)
argsot1(a)

In [47]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
import numpy as np

def concat(a, b):
  return np.concatenate((a, b))
concat(a,b)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
import numpy as np

def concat_0(a, b):
  return np.concatenate((a, b), axis=0)
concat_0(a,b)
# Note: You can do the same function using stacking, discover and try that :)


array([[-4,  6,  8],
       [ 9,  3,  1],
       [ 1,  8,  5],
       [11, 16, 18],
       [90, 37, 81],
       [61, 48, 75]])

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [31]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [33]:
# Write a NumPy function to get the Number of dimensions
def dim(arr):
    return arr.ndim
# Write a NumPy function to get the Shape of the array
def shape(arr):
  return np.shape(arr)
# Write a NumPy function to get the Size of the array
def size(arr):
  return arr.size
print(dim(a))
print(shape(a))
print(size(a))

2
(3, 3)
9


In [34]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape(arr):
  return arr.reshape(1,9)
print(reshape(a))

[[4 6 8 9 3 1 1 8 5]]


In [36]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
def adddim(a):
  return np.expand_dims(a,axis=1)
print(adddim(a))

[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [28]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [29]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists

# Show all three - indexing by a integer, indexing by a tuple, using range

row_1 = a[1]


element = a[2, 1]

slice_rows = a[0:2]
slice_columns = a[:, 1:3]

print(row_1)
print(element)
print(slice_rows)
print(slice_columns)

[0 3 1]
8
[[4 6 0]
 [0 3 1]]
[[6 0]
 [3 1]
 [8 5]]


In [30]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
val = a[a > 4]
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
val2 = a[(a > 4) & (a % 2 == 0)]
print(val)
print(val2)

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [27]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [28]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
arr=a.copy()
arr[:,:]=arr[:,:]+1
print(arr)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [21]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [22]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df = pd.DataFrame(iris_2d)
def droprows(df):
 return df.dropna()
droprows(df)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [23]:
# Write a Pandas function to find the correlation between the first two columns.
def calc(df):
    first= df.iloc[:, 0]
    sec = df.iloc[:, 1]
    corr= first.corr(sec)
    return corr
calc(df)

np.float64(-0.10936924995064937)

In [25]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
import pandas as pd
def stats(df):
  col3=df.iloc[:,2]
  mean=col3.mean()
  med=col3.median()
  std=col3.std()
  return mean,med,std
stats(df)

(np.float64(3.758666666666666), 4.35, 1.7644204199522617)

In [27]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
import pandas as pd
import math
df = pd.DataFrame(iris_2d, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
def add(df):
    df['volume'] = (math.pi * df['petal_length'] * df['sepal_length']**2) / 3
    return df
add(df)
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

sepal_length  sepal_width  petal_length  petal_width      volume
0             5.1          3.5           1.4          0.2   38.132652
1             4.9          3.0           1.4          0.2   35.200498
2             4.7          3.2           1.3          0.2   30.072372
3             4.6          3.1           1.5          0.2   33.238050
4             5.0          3.6           1.4          0.2   36.651914
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3  244.445230
146           6.3          2.5           5.0          1.9  207.816354
147           6.5          3.0           5.2          2.0  230.069302
148           6.2          3.4           5.4          2.3  217.373079
149           5.9          3.0           5.1          1.8  185.910028

[150 rows x 5 columns]

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [3]:
import numpy as np
x = np.arange(4, dtype=np.int64)
arr=x.copy()
arr[:]=1
print(arr)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [5]:
import numpy as np
x =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array1 = x[:4]
array2 = x[4:6]
array3 = x[6:]

print("Array 1:", array1)
print("Array 2:", array2)
print("Array 3:", array3)

Array 1: [1 2 3 4]
Array 2: [5 6]
Array 3: [7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [18]:
import numpy as np
arr=np.random.randint(0,10,10).reshape(2,5)
min=np.min(arr,axis=1)
max_indices = np.argmax(arr, axis=1)
max=np.max(arr,axis=1)
min_indices = np.argmin(arr, axis=1)
print(arr)
print(min)
print(max)
print(max_indices)
print(min_indices)

[[9 4 4 3 5]
 [4 4 0 8 0]]
[3 0]
[9 8]
[0 3]
[3 2]


### Pandas

Run the following load command and solve the following questions

In [8]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [9]:
import pandas as pd
dff=pd.DataFrame(iris, columns=names)
def count(df, species):
    return df[species].nunique()
for i in names:
  print(count(dff,i))

35
23
43
22
3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [14]:
import pandas as pd
import numpy as np
dff=pd.DataFrame(iris, columns=names)
def bin(df):
  bins = [0, 3, 5, np.inf]
  labels = ['small', 'medium', 'large']

  df_petal = df.iloc[:, 2].astype(str).astype(float)
  binned= pd.cut(df_petal, bins=bins, labels=labels, right=False)

  return binned
bin(dff)

0      small
1      small
2      small
3      small
4      small
       ...  
145    large
146    large
147    large
148    large
149    large
Name: petallength, Length: 150, dtype: category
Categories (3, object): ['small' < 'medium' < 'large']

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [15]:
import pandas as pd
import numpy as np
dff=pd.DataFrame(iris, columns=names)
def most(df):

  df_petal = df.iloc[:, 2].astype(str).astype(float)
  most_frequent = df_petal.value_counts().idxmax()

  return most_frequent
most(dff)


np.float64(1.5)