Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [3]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
list1=np.arange(1,6,1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
list2=np.zeros((3,3))

print(list1)
print(list2)

[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
def f1():
  return np.random.rand(3,4)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def f2():
  return np.zeros((3,4))
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
def f3():
  return np.ones((3,4))

In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
def f4(start, end , interval):
  return np.arange(start,end, interval)

# Hint : Use np.arange or np.linspace

### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def f1(a,b):
    return a+b
def f2(a,b):
    return a-b
def f3(a,b):
    return a*b
def f4(a,b):
    return a/b


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
def g1(a):
  return np.sum(a,axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
def g2(a):
  return np.sum(a,axis=1)

In [ ]:
# Write a NumPy function to reverse the array 'a'
def h1(a):
  return np.flip(a)
# Write a NumPy funcdef h1(a):
def h2(a):
  return np.flip(a,axis=0)
# Write a NumPy function to reverse the array 'a' along axis=1
def h3(a):
  return np.flip(a,axis=1)

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
def b1(a):
  return np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
def b2(a):
  return np.sort(a,axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
def b3(a):
  return np.sort(a,axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
def b4(a):
  return np.sort(a, axis=0)[::-1]

In [ ]:
# Write a NumPy function to argsort the array along axis=0
def c2(a):
  return np.argsort(a,axis=0)
# Write a NumPy function to argsort the array along axis=1
def c3(a):
  return np.argsort(a,axis=1)

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def conc1(a, b):
    return np.concatenate((a, b), axis=0)
# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
def gd(arr):
    return arr.ndim
# Write a NumPy function to get the Shape of the array
def gs(arr):

    return arr.shape
# Write a NumPy function to get the Size of the array
def gsi(arr):

    return arr.size

In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def r(arr):
    return arr.reshape(1,9)

In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
def gd1(arr):
  return arr[:,np.newaxis]
def gd2(arr):
  return arr[np.newaxis,:]
# Note : Show atleast two different ways of doing this


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
arr = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
def demonstrate_numpy_indexing(row,tupled):
    print( arr[row])

    print( arr[tupled])

    print(arr[0:2, 1:3])



In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
def s1(arr):

    return arr[arr > 4]
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2

def s2(arr):

    return arr[(arr > 4) & (arr % 2 == 0)]



### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def copy(a):

    a_copy = np.copy(a)
    a_copy += 1
    return a_copy

print(copy(a))

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [4]:
import pandas as pd

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [6]:
# Write a Pandas function to drop rows that contain a missing value.
def dropnullrow(df):
  df.dropna()


In [7]:
# Write a Pandas function to find the correlation between the first two columns.
def correlation(df):
  col1=df.iloc[:,0]
  col2=df.iloc[:,1]
  return col1.corr(col2)

In [8]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
def find_M_M_S(df):
  return [df.iloc[:,2].mean(),df.iloc[:,2].median(),df.iloc[:,2].std()]

In [14]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
def add_column(iris_2d):




    df = pd.DataFrame(iris_2d, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])


    df['volume'] = (3.14 * df['petal_length'] * df['sepal_length']**2) / 3

    return df
add_column(iris_2d).head()

# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

sepal_length  sepal_width  petal_length  petal_width     volume
0           5.1          3.5           1.4          0.2  38.113320
1           4.9          3.0           1.4          0.2  35.182653
2           4.7          3.2           1.3          0.2  30.057127
3           4.6          3.1           1.5          0.2  33.221200
4           5.0          3.6           1.4          0.2  36.633333

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [17]:
np.ones((4,),dtype=np.int64)

array([1, 1, 1, 1])

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [19]:
a=np.arange(1,10,1)
b=a[0:4]
c=a[4:6]
d=a[6:9]
b

array([1, 2, 3, 4])

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [22]:
x = np.random.uniform(0, 10, (2, 5))


max = np.max(x, axis=1)
min = np.min(x, axis=1)


max_indice = np.argmax(x, axis=1)
min_indice = np.argmin(x, axis=1)
data = {
    "max_indices": max_indice,
    "max_values": max,
    "min_indices": min_indice,
    "min_values": min
}
data

{'max_indices': array([1, 4]),
 'max_values': array([9.61822668, 9.08501769]),
 'min_indices': array([4, 2]),
 'min_values': array([0.98717137, 3.04647643])}

### Pandas

Run the following load command and solve the following questions

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [40]:
data=[]
for length in df['petallength']:
  if(float(length.decode('utf-8'))<3):
    data.append("small")

  elif(float(length.decode('utf-8'))>=5):
    data.append("large")
  else:
    data.append("medium")
data


['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'mediu

In [26]:
df=pd.DataFrame(iris,columns=names)
df['species'].unique().size

3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [42]:
df['petallength'].mode()

0    b'1.5'
Name: petallength, dtype: object