<a href="https://colab.research.google.com/github/gaixen/Frames-to-Fables_assignment01/blob/main/Assignment%201/solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [45]:
import numpy as np

In [4]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr=np.array([1,2,3,4,5])
print(arr)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr=np.random.rand(3,4)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr1=np.zeros((3,4))
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr2=np.ones((3,4))
print(arr,arr1,arr2)

[[0.52710579 0.59193839 0.94284405 0.61317933]
 [0.8748032  0.40810892 0.87882247 0.5259116 ]
 [0.89603963 0.06166348 0.692111   0.98091819]] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
arr=np.arange(0,12,2)
print(arr)
arr1=np.linspace(0,12,7)
print(arr1)
# Hint : Use np.arange or np.linspace

[ 0  2  4  6  8 10]
[ 0.  2.  4.  6.  8. 10. 12.]


### Basic array operations
- algebraic operations
- logical operations

In [7]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [8]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
c=np.add(a,b)
d=np.add(a,-b)
e=np.multiply(a,b)
f=np.divide(a,b)
print(c)
print(d)
print(e)
print(f)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [9]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
sum0=np.sum(a,axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
sum1=np.sum(a,axis=1)
print(sum0,sum1)

[ 6 17 14] [10 13 14]


In [10]:
print(a)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]


In [11]:
# Write a NumPy function to reverse the array 'a'
#arr_rev=a[::-1]
arr_rev=np.flip(a)
print(arr_rev)
# Write a NumPy function to reverse the array 'a' along axis=0
reva0=np.flip(a,axis=0)
print(reva0)
# Write a NumPy function to reverse the array 'a' along axis=1
reva1=np.flip(a,axis=1)
print(reva1)

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [12]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [13]:
# Write a NumPy function to sort the array 'a'
sorted_a=np.sort(a)
print(sorted_a)
# Write a NumPy function to sort the array 'a' along axis=0
sorted0_a=np.sort(a,axis=0)
print(sorted0_a)
# Write a NumPy function to sort the array 'a' along axis=1
sorted1_a=np.sort(a,axis=1)
print(sorted1_a)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
sorteddes_a=np.sort(a,axis=0)[::-1]
print(sorteddes_a)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [14]:
# Write a NumPy function to argsort the array along axis=0
argsort_a=np.argsort(a,axis=0)
print(argsort_a)
# Write a NumPy function to argsort the array along axis=1
argsort1_A=np.argsort(a,axis=1)
print(argsort1_A)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [15]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
ab=np.concatenate((a,b))
print(ab)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
ab1=np.concatenate((a,b),axis=0)
print(ab1)
# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [16]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [17]:
# Write a NumPy function to get the Number of dimensions
dimension=np.ndim(a)
# Write a NumPy function to get the Shape of the array
shape=np.shape(a)
# Write a NumPy function to get the Size of the array
size=np.size(a)
print(dimension,shape,size)

2 (3, 3) 9


In [18]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
np.reshape(a,(1,9))

array([[4, 6, 8, 9, 3, 1, 1, 8, 5]])

In [19]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
new_axis1=np.expand_dims(a,axis=1)
new_axis2=a[:np.newaxis:]
print(new_axis1 )
print(new_axis2)

[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]
[[4 6 8]
 [9 3 1]
 [1 8 5]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [20]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [21]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
#indexing by a integer
index_int=a[1][1]
print(index_int)
#indexing by a tuple
index_tuple=a[1,1]
print(index_tuple)
#using range
index_range=a[0:2,1:3]
print(index_range)

3
3
[[6 0]
 [3 1]]


In [22]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a%4==0])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4) & (a%2==0)])

[4 0 0 8]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [23]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [24]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
a_replica=a.copy()
a_replica+=1
print(a_replica)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



In [82]:
import pandas as pd

#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [26]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [36]:
# Write a Pandas function to drop rows that contain a missing value.
def cleaned_dataset(df):
  return df.dropna()
cleaned_dataset(pd.DataFrame(iris_2d))

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [39]:
# Write a Pandas function to find the correlation between the first two columns.
iris_2d=pd.DataFrame(iris_2d,columns=['sepallength','sepalwidth','petallength','petalwidth'])
iris_2d[['sepallength','sepalwidth']].corr()

sepallength  sepalwidth
sepallength     1.000000   -0.109369
sepalwidth     -0.109369    1.000000

In [43]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
a=iris_2d['petallength'].mean()
b=iris_2d['petallength'].median()
c=iris_2d['petallength'].std()
print(a,b,c)

3.758666666666666 4.35 1.7644204199522617


In [44]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
iris_2d['volume']=(np.pi*iris_2d['petallength']*iris_2d['sepallength']**2)/3
iris_2d

sepallength  sepalwidth  petallength  petalwidth      volume
0            5.1         3.5          1.4         0.2   38.132652
1            4.9         3.0          1.4         0.2   35.200498
2            4.7         3.2          1.3         0.2   30.072372
3            4.6         3.1          1.5         0.2   33.238050
4            5.0         3.6          1.4         0.2   36.651914
..           ...         ...          ...         ...         ...
145          6.7         3.0          5.2         2.3  244.445230
146          6.3         2.5          5.0         1.9  207.816354
147          6.5         3.0          5.2         2.0  230.069302
148          6.2         3.4          5.4         2.3  217.373079
149          5.9         3.0          5.1         1.8  185.910028

[150 rows x 5 columns]

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [85]:
x = np.arange(4, dtype=np.int64)
ones_like=np.ones_like(x)
ones_like

array([1, 1, 1, 1])

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [58]:
x=[i+1 for i in range(10)]
x1=x[:4]
x2=x[4:6]
x3=x[6:9]
print(x1,x2,x3)

[1, 2, 3, 4] [5, 6] [7, 8, 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [66]:
x=np.random.rand(2,5)*10
print(x)
print(np.max(x,axis=1))
print(np.min(x,axis=1))

[[4.63538224 1.89130166 3.25362956 8.8986795  8.03274046]
 [0.23749445 5.70985101 8.61781704 6.43203343 1.78341541]]
[8.8986795  8.61781704]
[1.89130166 0.23749445]


### Pandas

Run the following load command and solve the following questions

In [94]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [95]:
df=pd.DataFrame(iris,columns=names)
df_norepeat=df['species'].nunique()
print(df_norepeat)
print(df.drop_duplicates(subset=['species']))

3
    sepallength sepalwidth petallength petalwidth             species
0        b'5.1'     b'3.5'      b'1.4'     b'0.2'      b'Iris-setosa'
50       b'7.0'     b'3.2'      b'4.7'     b'1.4'  b'Iris-versicolor'
100      b'6.3'     b'3.3'      b'6.0'     b'2.5'   b'Iris-virginica'


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [99]:
df['petallength'] = pd.to_numeric(df['petallength'])
df['petallength_category'] = pd.cut(
    df['petallength'],
    bins=[-np.inf, 3, 5, np.inf],
    labels=['small', 'medium', 'large']
)
df

sepallength sepalwidth  petallength petalwidth            species  \
0        b'5.1'     b'3.5'          1.4     b'0.2'     b'Iris-setosa'   
1        b'4.9'     b'3.0'          1.4     b'0.2'     b'Iris-setosa'   
2        b'4.7'     b'3.2'          1.3     b'0.2'     b'Iris-setosa'   
3        b'4.6'     b'3.1'          1.5     b'0.2'     b'Iris-setosa'   
4        b'5.0'     b'3.6'          1.4     b'0.2'     b'Iris-setosa'   
..          ...        ...          ...        ...                ...   
145      b'6.7'     b'3.0'          5.2     b'2.3'  b'Iris-virginica'   
146      b'6.3'     b'2.5'          5.0     b'1.9'  b'Iris-virginica'   
147      b'6.5'     b'3.0'          5.2     b'2.0'  b'Iris-virginica'   
148      b'6.2'     b'3.4'          5.4     b'2.3'  b'Iris-virginica'   
149      b'5.9'     b'3.0'          5.1     b'1.8'  b'Iris-virginica'   

    petallength_category  
0                  small  
1                  small  
2                  small  
3                  small  
4                  small  
..                   ...  
145                large  
146               medium  
147                large  
148                large  
149                large  

[150 rows x 6 columns]

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [100]:
print(df['petallength'].mode())

0    1.5
Name: petallength, dtype: float64
